// This file is generated by scripts/generate_schema_converters.py.
// Do not edit by hand.

import { ExtensionContext, Immutable, MessageEvent } from "@foxglove/extension";

type AnyMessage = Record<string, unknown>;
type FoxgloveTime = { sec: number; nsec: number };
type RosTime = { sec: number; nanosec: number };
type GeoJsonFieldConfig = {
  path: readonly string[];
  mode: "location" | "location_array" | "polygon";
  field: string;
  color: string;
};

const AUDIO_FORMAT = "pcm-s16";
const AUDIO_SAMPLE_RATE = 48000;
const AUDIO_CHANNELS = 1;

function asObject(value: unknown): AnyMessage | undefined {
  if (typeof value !== "object" || value == undefined || Array.isArray(value)) {
    return undefined;
  }
  return value as AnyMessage;
}

function eventTime(event: Immutable<MessageEvent<unknown>>): FoxgloveTime {
  const stamp = event.publishTime ?? event.receiveTime;
  return {
    sec: Number(stamp?.sec ?? 0),
    nsec: Number(stamp?.nsec ?? 0),
  };
}

function eventRosTime(event: Immutable<MessageEvent<unknown>>): RosTime {
  const stamp = eventTime(event);
  return {
    sec: stamp.sec,
    nanosec: stamp.nsec,
  };
}

function normalizeBytes(value: unknown): Uint8Array {
  if (value instanceof Uint8Array) {
    return value;
  }

  if (Array.isArray(value)) {
    return new Uint8Array(value as readonly number[]);
  }

  return new Uint8Array();
}

function getValuesAtPath(value: unknown, path: readonly string[]): unknown[] {
  if (value == undefined) {
    return [];
  }

  if (path.length === 0) {
    return Array.isArray(value) ? value : [value];
  }

  const [head, ...tail] = path;

  if (head == undefined) {
    return [];
  }

  if (Array.isArray(value)) {
    return value.flatMap((entry) => getValuesAtPath(entry, path));
  }

  const objectValue = asObject(value);
  if (objectValue == undefined) {
    return [];
  }

  return getValuesAtPath(objectValue[head], tail);
}

function getFirstAtPath(value: unknown, path: readonly string[]): unknown | undefined {
  return getValuesAtPath(value, path)[0];
}

function isFiniteNumber(value: unknown): value is number {
  return typeof value === "number" && Number.isFinite(value);
}

function isValidNavSatFix(value: unknown): value is AnyMessage {
  const fix = asObject(value);
  if (fix == undefined) {
    return false;
  }

  return (
    isFiniteNumber(fix.latitude) &&
    isFiniteNumber(fix.longitude) &&
    Math.abs(fix.latitude) <= 90 &&
    Math.abs(fix.longitude) <= 180
  );
}

function navSatFixToCoordinates(fix: AnyMessage): number[] {
  const coordinates = [fix.longitude as number, fix.latitude as number];

  if (isFiniteNumber(fix.altitude)) {
    coordinates.push(fix.altitude);
  }

  return coordinates;
}

function geoJsonStyle(color: string): AnyMessage {
  return {
    color,
    markerColor: color,
    stroke: color,
    fill: color,
    fillOpacity: 0.25,
    strokeWidth: 3,
  };
}

function geoJsonProperties(config: GeoJsonFieldConfig, event: Immutable<MessageEvent<unknown>>, index?: number): AnyMessage {
  return {
    ...geoJsonStyle(config.color),
    name: index == undefined ? config.field : `${config.field} ${index}`,
    field: config.field,
    mode: config.mode,
    index,
    source_topic: event.topic,
    color: config.color,
  };
}

function emptyFeatureCollection(event: Immutable<MessageEvent<unknown>>): unknown {
  return {
    timestamp: eventTime(event),
    frame_id: "",
    geojson: JSON.stringify({
      type: "FeatureCollection",
      features: [],
    }),
  };
}

function convertGeoJsonFields(
  message: Immutable<unknown>,
  event: Immutable<MessageEvent<unknown>>,
  configs: readonly GeoJsonFieldConfig[],
): unknown {
  const features: unknown[] = [];
  let frameId = "";

  for (const config of configs) {
    const fixes = getValuesAtPath(message, config.path).filter(isValidNavSatFix);

    if (fixes.length === 0) {
      continue;
    }

    if (frameId.length === 0) {
      const header = asObject(asObject(fixes[0])?.header);
      frameId = String(header?.frame_id ?? "");
    }

    if (config.mode === "polygon") {
      const ring = fixes.map(navSatFixToCoordinates);
      const first = ring[0];
      const last = ring[ring.length - 1];

      if (first != undefined && last != undefined) {
        if (first[0] !== last[0] || first[1] !== last[1]) {
          ring.push([...first]);
        }
      }

      if (ring.length >= 4) {
        features.push({
          type: "Feature",
          geometry: {
            type: "Polygon",
            coordinates: [ring],
          },
          properties: geoJsonProperties(config, event),
        });
      }

      continue;
    }

    fixes.forEach((fix, index) => {
      const objectFix = fix as AnyMessage;
      features.push({
        type: "Feature",
        geometry: {
          type: "Point",
          coordinates: navSatFixToCoordinates(objectFix),
        },
        properties: {
          ...geoJsonProperties(config, event, index),
          latitude: objectFix.latitude,
          longitude: objectFix.longitude,
          altitude: objectFix.altitude,
        },
      });
    });
  }

  if (features.length === 0) {
    return emptyFeatureCollection(event);
  }

  return {
    timestamp: eventTime(event),
    frame_id: frameId,
    geojson: JSON.stringify({
      type: "FeatureCollection",
      features,
    }),
  };
}

function convertRawAudio(
  message: Immutable<unknown>,
  event: Immutable<MessageEvent<unknown>>,
  path: readonly string[],
): unknown {
  const value = getFirstAtPath(message, path);
  const bytes = normalizeBytes(value);

  if (bytes.length === 0) {
    return undefined;
  }

  const root = asObject(message);
  const audioStart = asObject(root?.audio_start);
  const timestamp =
    audioStart != undefined
      ? {
          sec: Number(audioStart.sec ?? 0),
          nsec: Number(audioStart.nsec ?? audioStart.nanosec ?? 0),
        }
      : eventTime(event);

  return {
    timestamp,
    data: bytes,
    format: AUDIO_FORMAT,
    sample_rate: AUDIO_SAMPLE_RATE,
    number_of_channels: AUDIO_CHANNELS,
  };
}

function convertTextLog(
  message: Immutable<unknown>,
  event: Immutable<MessageEvent<unknown>>,
  path: readonly string[],
  fieldLabel: string,
): unknown {
  const value = getFirstAtPath(message, path);

  if (value == undefined || String(value).length === 0) {
    return undefined;
  }

  return {
    timestamp: eventTime(event),
    level: 2,
    message: String(value),
    name: fieldLabel,
    file: "",
    line: 0,
  };
}

function convertPassThrough(
  message: Immutable<unknown>,
  event: Immutable<MessageEvent<unknown>>,
  path: readonly string[],
  target: string,
): unknown {
  const value = getFirstAtPath(message, path);

  if (value == undefined) {
    return undefined;
  }

  const objectValue = asObject(value);

  if (objectValue != undefined && target === "image") {
    return {
      ...objectValue,
      header:
        objectValue.header ??
        {
          stamp: eventRosTime(event),
          frame_id: "",
        },
      data: normalizeBytes(objectValue.data),
    };
  }

  return value;
}

export function registerGeneratedSchemaConverters(extensionContext: ExtensionContext): void {
  // Aggregated GeoJSON converter for cdcl_umd_msgs/msg/Assessment
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/Assessment",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJsonFields(message, event, [
      { path: ["location"], mode: "location", field: "location", color: "#800000" }
    ]),
  });
  // Aggregated GeoJSON converter for cdcl_umd_msgs/msg/CameraFOV
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CameraFOV",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJsonFields(message, event, [
      { path: ["fov_polygon"], mode: "polygon", field: "fov_polygon", color: "#008080" }
    ]),
  });
  // Aggregated GeoJSON converter for cdcl_umd_msgs/msg/CasualtyImage
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CasualtyImage",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJsonFields(message, event, [
      { path: ["position"], mode: "location", field: "position", color: "#4363d8" }
    ]),
  });
  // Aggregated GeoJSON converter for cdcl_umd_msgs/msg/CasualtyImageCompressed
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CasualtyImageCompressed",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJsonFields(message, event, [
      { path: ["position"], mode: "location", field: "position", color: "#ffd8b1" }
    ]),
  });
  // Aggregated GeoJSON converter for cdcl_umd_msgs/msg/CasualtyLocation
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CasualtyLocation",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJsonFields(message, event, [
      { path: ["position"], mode: "location", field: "position", color: "#3cb44b" }
    ]),
  });
  // Aggregated GeoJSON converter for cdcl_umd_msgs/msg/CasualtyReport
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CasualtyReport",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJsonFields(message, event, [
      { path: ["position"], mode: "location", field: "position", color: "#f032e6" },
      { path: ["position_submitted"], mode: "location", field: "position_submitted", color: "#46f0f0" }
    ]),
  });
  // Aggregated GeoJSON converter for cdcl_umd_msgs/msg/KnownCasualtyLocations
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/KnownCasualtyLocations",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJsonFields(message, event, [
      { path: ["casualty_locations", "position"], mode: "location_array", field: "casualty_locations.position", color: "#000075" }
    ]),
  });
  // Aggregated GeoJSON converter for cdcl_umd_msgs/msg/Observation
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/Observation",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJsonFields(message, event, [
      { path: ["position"], mode: "location", field: "position", color: "#800000" }
    ]),
  });
  // Aggregated GeoJSON converter for cdcl_umd_msgs/msg/Submission
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/Submission",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJsonFields(message, event, [
      { path: ["assessment", "location"], mode: "location", field: "assessment.location", color: "#f58231" }
    ]),
  });
  // Aggregated GeoJSON converter for cdcl_umd_msgs/msg/SupervisorInterfaceSettings
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/SupervisorInterfaceSettings",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJsonFields(message, event, [
      { path: ["geo_fence"], mode: "polygon", field: "geo_fence", color: "#9a6324" },
      { path: ["search_domain"], mode: "polygon", field: "search_domain", color: "#46f0f0" },
      { path: ["launch_zone"], mode: "polygon", field: "launch_zone", color: "#000075" },
      { path: ["known_casualties", "position"], mode: "location_array", field: "known_casualties.position", color: "#008080" },
      { path: ["known_casualties", "position_submitted"], mode: "location_array", field: "known_casualties.position_submitted", color: "#46f0f0" }
    ]),
  });
  // Aggregated GeoJSON converter for cdcl_umd_msgs/msg/TargetBox
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/TargetBox",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJsonFields(message, event, [
      { path: ["target_location_altimeter_plane"], mode: "location", field: "target_location_altimeter_plane", color: "#911eb4" },
      { path: ["target_location_gimbal_plane"], mode: "location", field: "target_location_gimbal_plane", color: "#ffd8b1" },
      { path: ["target_location_rangefinder"], mode: "location", field: "target_location_rangefinder", color: "#9a6324" }
    ]),
  });
  // Aggregated GeoJSON converter for cdcl_umd_msgs/msg/TargetBoxArray
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/TargetBoxArray",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJsonFields(message, event, [
      { path: ["uav_gps_location"], mode: "location", field: "uav_gps_location", color: "#aaffc3" },
      { path: ["uav_target_boxes", "target_location_altimeter_plane"], mode: "location_array", field: "uav_target_boxes.target_location_altimeter_plane", color: "#000075" },
      { path: ["uav_target_boxes", "target_location_gimbal_plane"], mode: "location_array", field: "uav_target_boxes.target_location_gimbal_plane", color: "#ffd8b1" },
      { path: ["uav_target_boxes", "target_location_rangefinder"], mode: "location_array", field: "uav_target_boxes.target_location_rangefinder", color: "#911eb4" }
    ]),
  });
  // Aggregated GeoJSON converter for cdcl_umd_msgs/msg/TargetHistoryArray
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/TargetHistoryArray",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJsonFields(message, event, [
      { path: ["target_locations", "target_location_intrinsics"], mode: "location_array", field: "target_locations.target_location_intrinsics", color: "#800000" },
      { path: ["target_locations", "target_location_topo"], mode: "location_array", field: "target_locations.target_location_topo", color: "#aaffc3" },
      { path: ["target_locations", "target_location_gimbal_plane"], mode: "location_array", field: "target_locations.target_location_gimbal_plane", color: "#e6194b" },
      { path: ["target_locations", "target_location_rangefinder"], mode: "location_array", field: "target_locations.target_location_rangefinder", color: "#e6beff" }
    ]),
  });
  // Aggregated GeoJSON converter for cdcl_umd_msgs/msg/TargetLocation
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/TargetLocation",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJsonFields(message, event, [
      { path: ["target_location_intrinsics"], mode: "location", field: "target_location_intrinsics", color: "#fffac8" },
      { path: ["target_location_topo"], mode: "location", field: "target_location_topo", color: "#800000" },
      { path: ["target_location_gimbal_plane"], mode: "location", field: "target_location_gimbal_plane", color: "#808000" },
      { path: ["target_location_rangefinder"], mode: "location", field: "target_location_rangefinder", color: "#3cb44b" }
    ]),
  });
  // Aggregated GeoJSON converter for cdcl_umd_msgs/msg/Waypoint
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/Waypoint",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJsonFields(message, event, [
      { path: ["position"], mode: "location", field: "position", color: "#f032e6" }
    ]),
  });
  // Aggregated GeoJSON converter for cdcl_umd_msgs/msg/WaypointArray
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/WaypointArray",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJsonFields(message, event, [
      { path: ["waypoints", "position"], mode: "location_array", field: "waypoints.position", color: "#46f0f0" }
    ]),
  });
  // CameraPose__pose__to__pose
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CameraPose",
    toSchemaName: "geometry_msgs/msg/Pose",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["pose"], "pose"),
  });
  // CasualtyImage__image__to__image
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CasualtyImage",
    toSchemaName: "sensor_msgs/msg/Image",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["image"], "image"),
  });
  // CasualtyImage__position_in_sensor_frame__to__point
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CasualtyImage",
    toSchemaName: "geometry_msgs/msg/Point",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["position_in_sensor_frame"], "point"),
  });
  // CasualtyImageCompressed__image__to__image
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CasualtyImageCompressed",
    toSchemaName: "sensor_msgs/msg/CompressedImage",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["image"], "image"),
  });
  // CasualtyImageCompressed__position_in_sensor_frame__to__point
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CasualtyImageCompressed",
    toSchemaName: "geometry_msgs/msg/Point",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["position_in_sensor_frame"], "point"),
  });
  // CasualtyReport__velocity__to__vector
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CasualtyReport",
    toSchemaName: "geometry_msgs/msg/Vector3",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["velocity"], "vector"),
  });
  // CenterROI__gimbal_attitude_quaternion__to__orientation
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CenterROI",
    toSchemaName: "geometry_msgs/msg/Quaternion",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["gimbal_attitude_quaternion"], "orientation"),
  });
  // CenterROI__uav_local_pose__to__odometry
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CenterROI",
    toSchemaName: "nav_msgs/msg/Odometry",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["uav_local_pose"], "odometry"),
  });
  // MosaicOverlay__overlay_png__to__image
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/MosaicOverlay",
    toSchemaName: "sensor_msgs/msg/CompressedImage",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["overlay_png"], "image"),
  });
  // ObservationDataSource__raw_audio__to__audio
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/ObservationDataSource",
    toSchemaName: "foxglove_msgs/msg/RawAudio",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertRawAudio(message, event, ["raw_audio"]),
  });
  // ObservationDataSource__audio_transcript__to__text
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/ObservationDataSource",
    toSchemaName: "foxglove_msgs/msg/Log",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertTextLog(message, event, ["audio_transcript"], "audio_transcript"),
  });
  // ObservationDataSource__image__to__image
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/ObservationDataSource",
    toSchemaName: "sensor_msgs/msg/CompressedImage",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["image"], "image"),
  });
  // ObservationDataSource__transcript__to__text
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/ObservationDataSource",
    toSchemaName: "foxglove_msgs/msg/Log",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertTextLog(message, event, ["transcript"], "transcript"),
  });
  // Submission__report_status__to__text
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/Submission",
    toSchemaName: "foxglove_msgs/msg/Log",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertTextLog(message, event, ["report_status"], "report_status"),
  });
  // SupervisorInterfaceSettings__known_casualties_velocity__to__vector_array
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/SupervisorInterfaceSettings",
    toSchemaName: "geometry_msgs/msg/Vector3",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["known_casualties", "velocity"], "vector_array"),
  });
  // TargetBoxArray__source_img__to__image
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/TargetBoxArray",
    toSchemaName: "sensor_msgs/msg/CompressedImage",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["source_img"], "image"),
  });
  // TargetBoxArray__uav_local_pose__to__odometry
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/TargetBoxArray",
    toSchemaName: "nav_msgs/msg/Odometry",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["uav_local_pose"], "odometry"),
  });
  // TargetBoxArray__gimbal_attitude_quaternion__to__orientation
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/TargetBoxArray",
    toSchemaName: "geometry_msgs/msg/Quaternion",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["gimbal_attitude_quaternion"], "orientation"),
  });
  // TargetHistoryArray__source_img__to__image
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/TargetHistoryArray",
    toSchemaName: "sensor_msgs/msg/CompressedImage",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["source_img"], "image"),
  });
  // Waypoint__orientation__to__orientation
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/Waypoint",
    toSchemaName: "geometry_msgs/msg/Quaternion",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["orientation"], "orientation"),
  });
}
