// This file is generated by scripts/generate_schema_converters.py.
// Do not edit by hand.

import { ExtensionContext, Immutable, MessageEvent } from "@foxglove/extension";

type AnyMessage = Record<string, unknown>;
type FoxgloveTime = { sec: number; nsec: number };
type RosTime = { sec: number; nanosec: number };

const AUDIO_FORMAT = "pcm-s16";
const AUDIO_SAMPLE_RATE = 48000;
const AUDIO_CHANNELS = 1;

function asObject(value: unknown): AnyMessage | undefined {
  if (typeof value !== "object" || value == undefined || Array.isArray(value)) {
    return undefined;
  }
  return value as AnyMessage;
}

function eventTime(event: Immutable<MessageEvent<unknown>>): FoxgloveTime {
  const stamp = event.publishTime ?? event.receiveTime;
  return {
    sec: Number(stamp?.sec ?? 0),
    nsec: Number(stamp?.nsec ?? 0),
  };
}

function eventRosTime(event: Immutable<MessageEvent<unknown>>): RosTime {
  const stamp = eventTime(event);
  return {
    sec: stamp.sec,
    nanosec: stamp.nsec,
  };
}

function normalizeBytes(value: unknown): Uint8Array {
  if (value instanceof Uint8Array) {
    return value;
  }

  if (Array.isArray(value)) {
    return new Uint8Array(value as readonly number[]);
  }

  return new Uint8Array();
}

function getValuesAtPath(value: unknown, path: readonly string[]): unknown[] {
  if (value == undefined) {
    return [];
  }

  if (path.length === 0) {
    return Array.isArray(value) ? value : [value];
  }

  const [head, ...tail] = path;

  if (head == undefined) {
    return [];
  }

  if (Array.isArray(value)) {
    return value.flatMap((entry) => getValuesAtPath(entry, path));
  }

  const objectValue = asObject(value);
  if (objectValue == undefined) {
    return [];
  }

  return getValuesAtPath(objectValue[head], tail);
}

function getFirstAtPath(value: unknown, path: readonly string[]): unknown | undefined {
  return getValuesAtPath(value, path)[0];
}

function isFiniteNumber(value: unknown): value is number {
  return typeof value === "number" && Number.isFinite(value);
}

function isValidNavSatFix(value: unknown): value is AnyMessage {
  const fix = asObject(value);
  if (fix == undefined) {
    return false;
  }

  return (
    isFiniteNumber(fix.latitude) &&
    isFiniteNumber(fix.longitude) &&
    Math.abs(fix.latitude) <= 90 &&
    Math.abs(fix.longitude) <= 180
  );
}

function navSatFixToCoordinates(fix: AnyMessage): number[] {
  const coordinates = [fix.longitude as number, fix.latitude as number];

  if (isFiniteNumber(fix.altitude)) {
    coordinates.push(fix.altitude);
  }

  return coordinates;
}

function emptyFeatureCollection(event: Immutable<MessageEvent<unknown>>): unknown {
  return {
    timestamp: eventTime(event),
    frame_id: "",
    geojson: JSON.stringify({
      type: "FeatureCollection",
      features: [],
    }),
  };
}

function convertGeoJson(
  message: Immutable<unknown>,
  event: Immutable<MessageEvent<unknown>>,
  path: readonly string[],
  mode: string,
  fieldLabel: string,
): unknown {
  const fixes = getValuesAtPath(message, path).filter(isValidNavSatFix);

  if (fixes.length === 0) {
    return emptyFeatureCollection(event);
  }

  const frameId =
    String(asObject(fixes[0])?.header != undefined ? asObject(asObject(fixes[0])?.header)?.frame_id ?? "" : "");

  if (mode === "polygon") {
    const ring = fixes.map(navSatFixToCoordinates);

    const first = ring[0];
    const last = ring[ring.length - 1];

    if (first != undefined && last != undefined) {
      if (first[0] !== last[0] || first[1] !== last[1]) {
        ring.push([...first]);
      }
    }

    if (ring.length < 4) {
      return emptyFeatureCollection(event);
    }

    return {
      timestamp: eventTime(event),
      frame_id: frameId,
      geojson: JSON.stringify({
        type: "FeatureCollection",
        features: [
          {
            type: "Feature",
            geometry: {
              type: "Polygon",
              coordinates: [ring],
            },
            properties: {
              name: fieldLabel,
              field: fieldLabel,
              source_topic: event.topic,
            },
          },
        ],
      }),
    };
  }

  return {
    timestamp: eventTime(event),
    frame_id: frameId,
    geojson: JSON.stringify({
      type: "FeatureCollection",
      features: fixes.map((fix, index) => {
        const objectFix = fix as AnyMessage;
        return {
          type: "Feature",
          geometry: {
            type: "Point",
            coordinates: navSatFixToCoordinates(objectFix),
          },
          properties: {
            name: `${fieldLabel} ${index}`,
            field: fieldLabel,
            index,
            source_topic: event.topic,
            latitude: objectFix.latitude,
            longitude: objectFix.longitude,
            altitude: objectFix.altitude,
          },
        };
      }),
    }),
  };
}

function convertRawAudio(
  message: Immutable<unknown>,
  event: Immutable<MessageEvent<unknown>>,
  path: readonly string[],
): unknown {
  const value = getFirstAtPath(message, path);
  const bytes = normalizeBytes(value);

  if (bytes.length === 0) {
    return undefined;
  }

  const root = asObject(message);
  const audioStart = asObject(root?.audio_start);
  const timestamp =
    audioStart != undefined
      ? {
          sec: Number(audioStart.sec ?? 0),
          nsec: Number(audioStart.nsec ?? audioStart.nanosec ?? 0),
        }
      : eventTime(event);

  return {
    timestamp,
    data: bytes,
    format: AUDIO_FORMAT,
    sample_rate: AUDIO_SAMPLE_RATE,
    number_of_channels: AUDIO_CHANNELS,
  };
}

function convertTextLog(
  message: Immutable<unknown>,
  event: Immutable<MessageEvent<unknown>>,
  path: readonly string[],
  fieldLabel: string,
): unknown {
  const value = getFirstAtPath(message, path);

  if (value == undefined || String(value).length === 0) {
    return undefined;
  }

  return {
    timestamp: eventTime(event),
    level: 2,
    message: String(value),
    name: fieldLabel,
    file: "",
    line: 0,
  };
}

function convertPassThrough(
  message: Immutable<unknown>,
  event: Immutable<MessageEvent<unknown>>,
  path: readonly string[],
  target: string,
): unknown {
  const value = getFirstAtPath(message, path);

  if (value == undefined) {
    return undefined;
  }

  const objectValue = asObject(value);

  if (objectValue != undefined && target === "image") {
    return {
      ...objectValue,
      header:
        objectValue.header ??
        {
          stamp: eventRosTime(event),
          frame_id: "",
        },
      data: normalizeBytes(objectValue.data),
    };
  }

  return value;
}

export function registerGeneratedSchemaConverters(extensionContext: ExtensionContext): void {
  // Assessment__location__to__location
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/Assessment",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJson(message, event, ["location"], "location", "location"),
  });
  // CameraFOV__fov_polygon__to__polygon
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CameraFOV",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJson(message, event, ["fov_polygon"], "polygon", "fov_polygon"),
  });
  // CameraPose__pose__to__pose
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CameraPose",
    toSchemaName: "geometry_msgs/msg/Pose",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["pose"], "pose"),
  });
  // CasualtyImage__image__to__image
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CasualtyImage",
    toSchemaName: "sensor_msgs/msg/Image",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["image"], "image"),
  });
  // CasualtyImage__position__to__location
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CasualtyImage",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJson(message, event, ["position"], "location", "position"),
  });
  // CasualtyImage__position_in_sensor_frame__to__point
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CasualtyImage",
    toSchemaName: "geometry_msgs/msg/Point",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["position_in_sensor_frame"], "point"),
  });
  // CasualtyImageCompressed__image__to__image
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CasualtyImageCompressed",
    toSchemaName: "sensor_msgs/msg/CompressedImage",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["image"], "image"),
  });
  // CasualtyImageCompressed__position__to__location
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CasualtyImageCompressed",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJson(message, event, ["position"], "location", "position"),
  });
  // CasualtyImageCompressed__position_in_sensor_frame__to__point
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CasualtyImageCompressed",
    toSchemaName: "geometry_msgs/msg/Point",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["position_in_sensor_frame"], "point"),
  });
  // CasualtyLocation__position__to__location
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CasualtyLocation",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJson(message, event, ["position"], "location", "position"),
  });
  // CasualtyReport__position__to__location
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CasualtyReport",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJson(message, event, ["position"], "location", "position"),
  });
  // CasualtyReport__velocity__to__vector
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CasualtyReport",
    toSchemaName: "geometry_msgs/msg/Vector3",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["velocity"], "vector"),
  });
  // CasualtyReport__position_submitted__to__location
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CasualtyReport",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJson(message, event, ["position_submitted"], "location", "position_submitted"),
  });
  // CenterROI__gimbal_attitude_quaternion__to__orientation
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CenterROI",
    toSchemaName: "geometry_msgs/msg/Quaternion",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["gimbal_attitude_quaternion"], "orientation"),
  });
  // CenterROI__uav_local_pose__to__odometry
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CenterROI",
    toSchemaName: "nav_msgs/msg/Odometry",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["uav_local_pose"], "odometry"),
  });
  // KnownCasualtyLocations__casualty_locations_position__to__location_array
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/KnownCasualtyLocations",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJson(message, event, ["casualty_locations", "position"], "location_array", "casualty_locations.position"),
  });
  // MosaicOverlay__overlay_png__to__image
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/MosaicOverlay",
    toSchemaName: "sensor_msgs/msg/CompressedImage",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["overlay_png"], "image"),
  });
  // Observation__position__to__location
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/Observation",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJson(message, event, ["position"], "location", "position"),
  });
  // ObservationDataSource__raw_audio__to__audio
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/ObservationDataSource",
    toSchemaName: "foxglove_msgs/msg/RawAudio",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertRawAudio(message, event, ["raw_audio"]),
  });
  // ObservationDataSource__audio_transcript__to__text
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/ObservationDataSource",
    toSchemaName: "foxglove_msgs/msg/Log",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertTextLog(message, event, ["audio_transcript"], "audio_transcript"),
  });
  // ObservationDataSource__image__to__image
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/ObservationDataSource",
    toSchemaName: "sensor_msgs/msg/CompressedImage",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["image"], "image"),
  });
  // ObservationDataSource__transcript__to__text
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/ObservationDataSource",
    toSchemaName: "foxglove_msgs/msg/Log",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertTextLog(message, event, ["transcript"], "transcript"),
  });
  // Submission__report_status__to__text
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/Submission",
    toSchemaName: "foxglove_msgs/msg/Log",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertTextLog(message, event, ["report_status"], "report_status"),
  });
  // Submission__assessment_location__to__location
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/Submission",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJson(message, event, ["assessment", "location"], "location", "assessment.location"),
  });
  // SupervisorInterfaceSettings__geo_fence__to__polygon
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/SupervisorInterfaceSettings",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJson(message, event, ["geo_fence"], "polygon", "geo_fence"),
  });
  // SupervisorInterfaceSettings__search_domain__to__polygon
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/SupervisorInterfaceSettings",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJson(message, event, ["search_domain"], "polygon", "search_domain"),
  });
  // SupervisorInterfaceSettings__launch_zone__to__polygon
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/SupervisorInterfaceSettings",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJson(message, event, ["launch_zone"], "polygon", "launch_zone"),
  });
  // SupervisorInterfaceSettings__known_casualties_position__to__location_array
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/SupervisorInterfaceSettings",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJson(message, event, ["known_casualties", "position"], "location_array", "known_casualties.position"),
  });
  // SupervisorInterfaceSettings__known_casualties_velocity__to__vector_array
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/SupervisorInterfaceSettings",
    toSchemaName: "geometry_msgs/msg/Vector3",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["known_casualties", "velocity"], "vector_array"),
  });
  // SupervisorInterfaceSettings__known_casualties_position_submitted__to__location_array
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/SupervisorInterfaceSettings",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJson(message, event, ["known_casualties", "position_submitted"], "location_array", "known_casualties.position_submitted"),
  });
  // TargetBox__target_location_altimeter_plane__to__location
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/TargetBox",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJson(message, event, ["target_location_altimeter_plane"], "location", "target_location_altimeter_plane"),
  });
  // TargetBox__target_location_gimbal_plane__to__location
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/TargetBox",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJson(message, event, ["target_location_gimbal_plane"], "location", "target_location_gimbal_plane"),
  });
  // TargetBox__target_location_rangefinder__to__location
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/TargetBox",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJson(message, event, ["target_location_rangefinder"], "location", "target_location_rangefinder"),
  });
  // TargetBoxArray__source_img__to__image
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/TargetBoxArray",
    toSchemaName: "sensor_msgs/msg/CompressedImage",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["source_img"], "image"),
  });
  // TargetBoxArray__uav_gps_location__to__location
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/TargetBoxArray",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJson(message, event, ["uav_gps_location"], "location", "uav_gps_location"),
  });
  // TargetBoxArray__uav_local_pose__to__odometry
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/TargetBoxArray",
    toSchemaName: "nav_msgs/msg/Odometry",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["uav_local_pose"], "odometry"),
  });
  // TargetBoxArray__gimbal_attitude_quaternion__to__orientation
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/TargetBoxArray",
    toSchemaName: "geometry_msgs/msg/Quaternion",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["gimbal_attitude_quaternion"], "orientation"),
  });
  // TargetBoxArray__uav_target_boxes_target_location_altimeter_plane__to__location_array
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/TargetBoxArray",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJson(message, event, ["uav_target_boxes", "target_location_altimeter_plane"], "location_array", "uav_target_boxes.target_location_altimeter_plane"),
  });
  // TargetBoxArray__uav_target_boxes_target_location_gimbal_plane__to__location_array
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/TargetBoxArray",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJson(message, event, ["uav_target_boxes", "target_location_gimbal_plane"], "location_array", "uav_target_boxes.target_location_gimbal_plane"),
  });
  // TargetBoxArray__uav_target_boxes_target_location_rangefinder__to__location_array
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/TargetBoxArray",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJson(message, event, ["uav_target_boxes", "target_location_rangefinder"], "location_array", "uav_target_boxes.target_location_rangefinder"),
  });
  // TargetHistoryArray__source_img__to__image
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/TargetHistoryArray",
    toSchemaName: "sensor_msgs/msg/CompressedImage",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["source_img"], "image"),
  });
  // TargetHistoryArray__target_locations_target_location_intrinsics__to__location_array
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/TargetHistoryArray",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJson(message, event, ["target_locations", "target_location_intrinsics"], "location_array", "target_locations.target_location_intrinsics"),
  });
  // TargetHistoryArray__target_locations_target_location_topo__to__location_array
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/TargetHistoryArray",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJson(message, event, ["target_locations", "target_location_topo"], "location_array", "target_locations.target_location_topo"),
  });
  // TargetHistoryArray__target_locations_target_location_gimbal_plane__to__location_array
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/TargetHistoryArray",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJson(message, event, ["target_locations", "target_location_gimbal_plane"], "location_array", "target_locations.target_location_gimbal_plane"),
  });
  // TargetHistoryArray__target_locations_target_location_rangefinder__to__location_array
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/TargetHistoryArray",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJson(message, event, ["target_locations", "target_location_rangefinder"], "location_array", "target_locations.target_location_rangefinder"),
  });
  // TargetLocation__target_location_intrinsics__to__location
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/TargetLocation",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJson(message, event, ["target_location_intrinsics"], "location", "target_location_intrinsics"),
  });
  // TargetLocation__target_location_topo__to__location
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/TargetLocation",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJson(message, event, ["target_location_topo"], "location", "target_location_topo"),
  });
  // TargetLocation__target_location_gimbal_plane__to__location
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/TargetLocation",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJson(message, event, ["target_location_gimbal_plane"], "location", "target_location_gimbal_plane"),
  });
  // TargetLocation__target_location_rangefinder__to__location
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/TargetLocation",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJson(message, event, ["target_location_rangefinder"], "location", "target_location_rangefinder"),
  });
  // Waypoint__position__to__location
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/Waypoint",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJson(message, event, ["position"], "location", "position"),
  });
  // Waypoint__orientation__to__orientation
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/Waypoint",
    toSchemaName: "geometry_msgs/msg/Quaternion",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["orientation"], "orientation"),
  });
  // WaypointArray__waypoints_position__to__location_array
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/WaypointArray",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJson(message, event, ["waypoints", "position"], "location_array", "waypoints.position"),
  });
}
