// This file is generated by scripts/generate_schema_converters.py.
// Do not edit by hand.

import { ExtensionContext, Immutable, MessageEvent } from "@foxglove/extension";

type AnyMessage = Record<string, unknown>;
type FoxgloveTime = { sec: number; nsec: number };
type RosTime = { sec: number; nanosec: number };
type GeoJsonFieldConfig = {
  path: readonly string[];
  mode: "location" | "location_array" | "polygon";
  field: string;
  color: string;
};
type Point2D = {
  x: number;
  y: number;
};

const AUDIO_FORMAT = "pcm-s16";
const AUDIO_SAMPLE_RATE = 48000;
const AUDIO_CHANNELS = 1;

const LINE_LOOP = 2;
const FONT_SIZE = 20;

function asObject(value: unknown): AnyMessage | undefined {
  if (typeof value !== "object" || value == undefined || Array.isArray(value)) {
    return undefined;
  }
  return value as AnyMessage;
}

function eventTime(event: Immutable<MessageEvent<unknown>>): FoxgloveTime {
  const stamp = event.publishTime ?? event.receiveTime;
  return {
    sec: Number(stamp?.sec ?? 0),
    nsec: Number(stamp?.nsec ?? 0),
  };
}

function eventRosTime(event: Immutable<MessageEvent<unknown>>): RosTime {
  const stamp = eventTime(event);
  return {
    sec: stamp.sec,
    nanosec: stamp.nsec,
  };
}

function normalizeBytes(value: unknown): Uint8Array {
  if (value instanceof Uint8Array) {
    return value;
  }

  if (Array.isArray(value)) {
    return new Uint8Array(value as readonly number[]);
  }

  return new Uint8Array();
}

function normalizeCompressedImageFormat(value: unknown): string {
  const format = String(value ?? "").toLowerCase();

  if (format.includes("jpg") || format.includes("jpeg")) {
    return "jpeg";
  }

  if (format.includes("png")) {
    return "png";
  }

  if (format.includes("tif") || format.includes("tiff")) {
    return "tiff";
  }

  // Most CDCL compressed images are JPEG if not otherwise specified.
  return "jpeg";
}

function getValuesAtPath(value: unknown, path: readonly string[]): unknown[] {
  if (value == undefined) {
    return [];
  }

  if (path.length === 0) {
    return Array.isArray(value) ? value : [value];
  }

  const [head, ...tail] = path;

  if (head == undefined) {
    return [];
  }

  if (Array.isArray(value)) {
    return value.flatMap((entry) => getValuesAtPath(entry, path));
  }

  const objectValue = asObject(value);
  if (objectValue == undefined) {
    return [];
  }

  return getValuesAtPath(objectValue[head], tail);
}

function getFirstAtPath(value: unknown, path: readonly string[]): unknown | undefined {
  return getValuesAtPath(value, path)[0];
}

function isFiniteNumber(value: unknown): value is number {
  return typeof value === "number" && Number.isFinite(value);
}

function isValidNavSatFix(value: unknown): value is AnyMessage {
  const fix = asObject(value);
  if (fix == undefined) {
    return false;
  }

  if (
    !isFiniteNumber(fix.latitude) ||
    !isFiniteNumber(fix.longitude) ||
    Math.abs(fix.latitude) > 90 ||
    Math.abs(fix.longitude) > 180
  ) {
    return false;
  }

  // Treat 0,0 as an unset/invalid localization.
  return !(fix.latitude === 0 && fix.longitude === 0);
}

function navSatFixToCoordinates(fix: AnyMessage): number[] {
  const coordinates = [fix.longitude as number, fix.latitude as number];

  if (isFiniteNumber(fix.altitude)) {
    coordinates.push(fix.altitude);
  }

  return coordinates;
}

function geoJsonStyle(color: string): AnyMessage {
  return {
    "marker-color": color,
    "marker-size": "large",
    "marker-symbol": "circle",
    "stroke-width": 4,
    "stroke-opacity": 1.0,
    "fill-opacity": 0.35,
    color,
    markerColor: color,
    strokeColor: color,
    fillColor: color,
    fillOpacity: 0.35,
    strokeWidth: 4,
    strokeOpacity: 1.0,
    radius: 8,
    opacity: 1.0,
    stroke: color,
    fill: color,
  };
}

function geoJsonProperties(config: GeoJsonFieldConfig, event: Immutable<MessageEvent<unknown>>, index?: number): AnyMessage {
  return {
    ...geoJsonStyle(config.color),
    name: index == undefined ? config.field : `${config.field} ${index}`,
    field: config.field,
    mode: config.mode,
    index,
    source_topic: event.topic,
    color: config.color,
  };
}

function emptyFeatureCollection(event: Immutable<MessageEvent<unknown>>): unknown {
  return {
    timestamp: eventTime(event),
    frame_id: "",
    geojson: JSON.stringify({
      type: "FeatureCollection",
      features: [],
    }),
  };
}

function convertGeoJsonFields(
  message: Immutable<unknown>,
  event: Immutable<MessageEvent<unknown>>,
  configs: readonly GeoJsonFieldConfig[],
): unknown {
  const features: unknown[] = [];
  let frameId = "";

  for (const config of configs) {
    const fixes = getValuesAtPath(message, config.path).filter(isValidNavSatFix);

    if (fixes.length === 0) {
      continue;
    }

    if (frameId.length === 0) {
      const header = asObject(asObject(fixes[0])?.header);
      frameId = String(header?.frame_id ?? "");
    }

    if (config.mode === "polygon") {
      const ring = fixes.map(navSatFixToCoordinates);
      const first = ring[0];
      const last = ring[ring.length - 1];

      if (first != undefined && last != undefined) {
        if (first[0] !== last[0] || first[1] !== last[1]) {
          ring.push([...first]);
        }
      }

      if (ring.length >= 4) {
        features.push({
          type: "Feature",
          geometry: {
            type: "Polygon",
            coordinates: [ring],
          },
          properties: geoJsonProperties(config, event),
        });
      }

      continue;
    }

    fixes.forEach((fix, index) => {
      const objectFix = fix as AnyMessage;
      features.push({
        type: "Feature",
        geometry: {
          type: "Point",
          coordinates: navSatFixToCoordinates(objectFix),
        },
        properties: {
          ...geoJsonProperties(config, event, index),
          latitude: objectFix.latitude,
          longitude: objectFix.longitude,
          altitude: objectFix.altitude,
        },
      });
    });
  }

  if (features.length === 0) {
    return emptyFeatureCollection(event);
  }

  return {
    timestamp: eventTime(event),
    frame_id: frameId,
    geojson: JSON.stringify({
      type: "FeatureCollection",
      features,
    }),
  };
}

function convertRawAudio(
  message: Immutable<unknown>,
  event: Immutable<MessageEvent<unknown>>,
  path: readonly string[],
): unknown {
  const value = getFirstAtPath(message, path);
  const bytes = normalizeBytes(value);

  if (bytes.length === 0) {
    return undefined;
  }

  const root = asObject(message);
  const audioStart = asObject(root?.audio_start);
  const timestamp =
    audioStart != undefined
      ? {
          sec: Number(audioStart.sec ?? 0),
          nsec: Number(audioStart.nsec ?? audioStart.nanosec ?? 0),
        }
      : eventTime(event);

  return {
    timestamp,
    data: bytes,
    format: AUDIO_FORMAT,
    sample_rate: AUDIO_SAMPLE_RATE,
    number_of_channels: AUDIO_CHANNELS,
  };
}

function convertTextLog(
  message: Immutable<unknown>,
  event: Immutable<MessageEvent<unknown>>,
  path: readonly string[],
  fieldLabel: string,
): unknown {
  const value = getFirstAtPath(message, path);

  if (value == undefined || String(value).length === 0) {
    return undefined;
  }

  return {
    timestamp: eventTime(event),
    level: 2,
    message: String(value),
    name: fieldLabel,
    file: "",
    line: 0,
  };
}

function convertPassThrough(
  message: Immutable<unknown>,
  event: Immutable<MessageEvent<unknown>>,
  path: readonly string[],
  target: string,
): unknown {
  const value = getFirstAtPath(message, path);

  if (value == undefined) {
    return undefined;
  }

  const objectValue = asObject(value);

  if (objectValue != undefined && target === "image") {
    const image: AnyMessage = {
      ...objectValue,
      header:
        objectValue.header ??
        {
          stamp: eventRosTime(event),
          frame_id: "",
        },
      data: normalizeBytes(objectValue.data),
    };

    // CompressedImage (no raw-image encoding field): Foxglove needs a
    // normalized format string to decode it.
    if (objectValue.encoding == undefined) {
      image.format = normalizeCompressedImageFormat(objectValue.format);
    }

    return image;
  }

  return value;
}

function rgba(r: number, g: number, b: number, a: number): Record<string, number> {
  return { r, g, b, a };
}

function rotatePoint(cx: number, cy: number, x: number, y: number, theta: number): Point2D {
  const cosTheta = Math.cos(theta);
  const sinTheta = Math.sin(theta);
  const dx = x - cx;
  const dy = y - cy;

  return {
    x: cx + cosTheta * dx - sinTheta * dy,
    y: cy + sinTheta * dx + cosTheta * dy,
  };
}

function headerStampOrEventTime(
  message: Immutable<unknown>,
  event: Immutable<MessageEvent<unknown>>,
): FoxgloveTime {
  const root = asObject(message);
  const header = asObject(root?.header);
  const stamp = asObject(header?.stamp);

  if (stamp != undefined) {
    return {
      sec: Number(stamp.sec ?? 0),
      nsec: Number(stamp.nsec ?? stamp.nanosec ?? 0),
    };
  }

  return eventTime(event);
}

// Stamps the extracted image with the parent message's header stamp — the
// same timestamp convertBoundingBoxAnnotations uses — so the parent message,
// the image, and its bounding-box annotations display synced in Foxglove.
function convertRootStampedImage(
  message: Immutable<unknown>,
  event: Immutable<MessageEvent<unknown>>,
  path: readonly string[],
): unknown {
  const value = getFirstAtPath(message, path);
  const objectValue = asObject(value);

  if (objectValue == undefined) {
    return undefined;
  }

  const stamp = headerStampOrEventTime(message, event);
  const header = asObject(objectValue.header);

  const image: AnyMessage = {
    ...objectValue,
    header: {
      frame_id: String(header?.frame_id ?? ""),
      stamp: { sec: stamp.sec, nanosec: stamp.nsec },
    },
    data: normalizeBytes(objectValue.data),
  };

  // CompressedImage (no raw-image encoding field): Foxglove needs a
  // normalized format string to decode it.
  if (objectValue.encoding == undefined) {
    image.format = normalizeCompressedImageFormat(objectValue.format);
  }

  return image;
}

function convertBoundingBoxAnnotations(
  message: Immutable<unknown>,
  event: Immutable<MessageEvent<unknown>>,
  path: readonly string[],
): unknown {
  const boxes = getValuesAtPath(message, path);

  if (boxes.length === 0) {
    return undefined;
  }

  const timestamp = headerStampOrEventTime(message, event);
  const points: Record<string, unknown>[] = [];
  const texts: Record<string, unknown>[] = [];

  boxes.forEach((boxValue, index) => {
    const targetBox = asObject(boxValue);
    const detectionConfidence = targetBox?.detection_confidence;
    const bbox = asObject(targetBox?.target_bbox);
    const center = asObject(bbox?.center);
    const position = asObject(center?.position);

    if (bbox == undefined || center == undefined || position == undefined) {
      return;
    }

    const cx = Number(position.x);
    const cy = Number(position.y);
    const theta = Number(center.theta ?? 0);
    const sizeX = Number(bbox.size_x);
    const sizeY = Number(bbox.size_y);

    if (
      !Number.isFinite(cx) ||
      !Number.isFinite(cy) ||
      !Number.isFinite(theta) ||
      !Number.isFinite(sizeX) ||
      !Number.isFinite(sizeY) ||
      sizeX <= 0 ||
      sizeY <= 0
    ) {
      return;
    }

    const halfX = sizeX / 2;
    const halfY = sizeY / 2;

    const corners = [
      { x: cx - halfX, y: cy - halfY },
      { x: cx + halfX, y: cy - halfY },
      { x: cx + halfX, y: cy + halfY },
      { x: cx - halfX, y: cy + halfY },
    ].map((point) => rotatePoint(cx, cy, point.x, point.y, theta));

    points.push({
      timestamp,
      type: LINE_LOOP,
      points: corners,
      thickness: 2,
      outline_color: rgba(0, 1, 0, 1),
      outline_colors: [],
      fill_color: rgba(0, 1, 0, 0.12),
    });

    texts.push({
      timestamp,
      position: corners[0],
      text: isFiniteNumber(detectionConfidence) ? `${index}: ${detectionConfidence.toFixed(2)}` : String(index),
      font_size: FONT_SIZE,
      text_color: rgba(1, 1, 1, 1),
      background_color: rgba(0, 0, 0, 0.6),
    });
  });

  if (points.length === 0 && texts.length === 0) {
    return undefined;
  }

  return {
    circles: [],
    points,
    texts,
  };
}

export function registerGeneratedSchemaConverters(extensionContext: ExtensionContext): void {
  // Aggregated GeoJSON converter for cdcl_umd_msgs/msg/Assessment
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/Assessment",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJsonFields(message, event, [
      { path: ["location"], mode: "location", field: "location", color: "#800000" }
    ]),
  });
  // Aggregated GeoJSON converter for cdcl_umd_msgs/msg/CameraFOV
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CameraFOV",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJsonFields(message, event, [
      { path: ["fov_polygon"], mode: "polygon", field: "fov_polygon", color: "#008080" }
    ]),
  });
  // Aggregated GeoJSON converter for cdcl_umd_msgs/msg/CasualtyImage
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CasualtyImage",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJsonFields(message, event, [
      { path: ["position"], mode: "location", field: "position", color: "#4363d8" }
    ]),
  });
  // Aggregated GeoJSON converter for cdcl_umd_msgs/msg/CasualtyImageCompressed
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CasualtyImageCompressed",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJsonFields(message, event, [
      { path: ["position"], mode: "location", field: "position", color: "#ffd8b1" }
    ]),
  });
  // Aggregated GeoJSON converter for cdcl_umd_msgs/msg/CasualtyImageWithLevel
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CasualtyImageWithLevel",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJsonFields(message, event, [
      { path: ["position"], mode: "location", field: "position", color: "#f58231" }
    ]),
  });
  // Aggregated GeoJSON converter for cdcl_umd_msgs/msg/CasualtyLocation
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CasualtyLocation",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJsonFields(message, event, [
      { path: ["position"], mode: "location", field: "position", color: "#3cb44b" }
    ]),
  });
  // Aggregated GeoJSON converter for cdcl_umd_msgs/msg/CasualtyReport
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CasualtyReport",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJsonFields(message, event, [
      { path: ["position"], mode: "location", field: "position", color: "#f032e6" },
      { path: ["position_submitted"], mode: "location", field: "position_submitted", color: "#46f0f0" }
    ]),
  });
  // Aggregated GeoJSON converter for cdcl_umd_msgs/msg/Geofence
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/Geofence",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJsonFields(message, event, [
      { path: ["coordinates"], mode: "location_array", field: "coordinates", color: "#46f0f0" }
    ]),
  });
  // Aggregated GeoJSON converter for cdcl_umd_msgs/msg/KnownCasualtyLocations
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/KnownCasualtyLocations",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJsonFields(message, event, [
      { path: ["casualty_locations", "position"], mode: "location_array", field: "casualty_locations.position", color: "#000075" }
    ]),
  });
  // Aggregated GeoJSON converter for cdcl_umd_msgs/msg/MedicUpdate
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/MedicUpdate",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJsonFields(message, event, [
      { path: ["position"], mode: "location", field: "position", color: "#e6beff" }
    ]),
  });
  // Aggregated GeoJSON converter for cdcl_umd_msgs/msg/Observation
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/Observation",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJsonFields(message, event, [
      { path: ["position"], mode: "location", field: "position", color: "#800000" }
    ]),
  });
  // Aggregated GeoJSON converter for cdcl_umd_msgs/msg/ObservationWithLevel
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/ObservationWithLevel",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJsonFields(message, event, [
      { path: ["position"], mode: "location", field: "position", color: "#f58231" }
    ]),
  });
  // Aggregated GeoJSON converter for cdcl_umd_msgs/msg/Submission
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/Submission",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJsonFields(message, event, [
      { path: ["assessment", "location"], mode: "location", field: "assessment.location", color: "#f58231" }
    ]),
  });
  // Aggregated GeoJSON converter for cdcl_umd_msgs/msg/SupervisorInterfaceSettings
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/SupervisorInterfaceSettings",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJsonFields(message, event, [
      { path: ["geo_fence"], mode: "polygon", field: "geo_fence", color: "#9a6324" },
      { path: ["search_domain"], mode: "polygon", field: "search_domain", color: "#46f0f0" },
      { path: ["launch_zone"], mode: "polygon", field: "launch_zone", color: "#000075" },
      { path: ["known_casualties", "position"], mode: "location_array", field: "known_casualties.position", color: "#008080" },
      { path: ["known_casualties", "position_submitted"], mode: "location_array", field: "known_casualties.position_submitted", color: "#46f0f0" },
      { path: ["exclusion_zones", "coordinates"], mode: "polygon", field: "exclusion_zones.coordinates", color: "#3cb44b" }
    ]),
  });
  // Aggregated GeoJSON converter for cdcl_umd_msgs/msg/TargetBox
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/TargetBox",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJsonFields(message, event, [
      { path: ["target_location_altimeter_plane"], mode: "location", field: "target_location_altimeter_plane", color: "#911eb4" }
    ]),
  });
  // Aggregated GeoJSON converter for cdcl_umd_msgs/msg/TargetHistoryArray
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/TargetHistoryArray",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJsonFields(message, event, [
      { path: ["target_locations", "target_location_intrinsics"], mode: "location_array", field: "target_locations.target_location_intrinsics", color: "#800000" },
      { path: ["target_locations", "target_location_topo"], mode: "location_array", field: "target_locations.target_location_topo", color: "#aaffc3" },
      { path: ["target_locations", "target_location_gimbal_plane"], mode: "location_array", field: "target_locations.target_location_gimbal_plane", color: "#e6194b" },
      { path: ["target_locations", "target_location_rangefinder"], mode: "location_array", field: "target_locations.target_location_rangefinder", color: "#e6beff" }
    ]),
  });
  // Aggregated GeoJSON converter for cdcl_umd_msgs/msg/TargetLocation
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/TargetLocation",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJsonFields(message, event, [
      { path: ["target_location_intrinsics"], mode: "location", field: "target_location_intrinsics", color: "#fffac8" },
      { path: ["target_location_topo"], mode: "location", field: "target_location_topo", color: "#800000" },
      { path: ["target_location_gimbal_plane"], mode: "location", field: "target_location_gimbal_plane", color: "#808000" },
      { path: ["target_location_rangefinder"], mode: "location", field: "target_location_rangefinder", color: "#3cb44b" }
    ]),
  });
  // Aggregated GeoJSON converter for cdcl_umd_msgs/msg/Waypoint
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/Waypoint",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJsonFields(message, event, [
      { path: ["position"], mode: "location", field: "position", color: "#f032e6" }
    ]),
  });
  // Aggregated GeoJSON converter for cdcl_umd_msgs/msg/WaypointArray
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/WaypointArray",
    toSchemaName: "foxglove_msgs/msg/GeoJSON",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertGeoJsonFields(message, event, [
      { path: ["waypoints", "position"], mode: "location_array", field: "waypoints.position", color: "#46f0f0" }
    ]),
  });
  // CameraPose__pose__to__pose
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CameraPose",
    toSchemaName: "geometry_msgs/msg/Pose",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["pose"], "pose"),
  });
  // CasualtyImage__image__to__image
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CasualtyImage",
    toSchemaName: "sensor_msgs/msg/Image",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["image"], "image"),
  });
  // CasualtyImage__position_in_sensor_frame__to__point
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CasualtyImage",
    toSchemaName: "geometry_msgs/msg/Point",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["position_in_sensor_frame"], "point"),
  });
  // CasualtyImageCompressed__image__to__image
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CasualtyImageCompressed",
    toSchemaName: "sensor_msgs/msg/CompressedImage",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["image"], "image"),
  });
  // CasualtyImageCompressed__position_in_sensor_frame__to__point
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CasualtyImageCompressed",
    toSchemaName: "geometry_msgs/msg/Point",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["position_in_sensor_frame"], "point"),
  });
  // CasualtyImageWithLevel__image__to__image
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CasualtyImageWithLevel",
    toSchemaName: "sensor_msgs/msg/Image",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["image"], "image"),
  });
  // CasualtyImageWithLevel__position_in_sensor_frame__to__point
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CasualtyImageWithLevel",
    toSchemaName: "geometry_msgs/msg/Point",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["position_in_sensor_frame"], "point"),
  });
  // CasualtyReport__velocity__to__vector
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CasualtyReport",
    toSchemaName: "geometry_msgs/msg/Vector3",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["velocity"], "vector"),
  });
  // CenterROI__gimbal_attitude_quaternion__to__orientation
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CenterROI",
    toSchemaName: "geometry_msgs/msg/Quaternion",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["gimbal_attitude_quaternion"], "orientation"),
  });
  // CenterROI__uav_local_pose__to__odometry
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/CenterROI",
    toSchemaName: "nav_msgs/msg/Odometry",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["uav_local_pose"], "odometry"),
  });
  // MosaicOverlay__overlay_png__to__image
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/MosaicOverlay",
    toSchemaName: "sensor_msgs/msg/CompressedImage",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["overlay_png"], "image"),
  });
  // ObservationDataSource__raw_audio__to__audio
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/ObservationDataSource",
    toSchemaName: "foxglove_msgs/msg/RawAudio",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertRawAudio(message, event, ["raw_audio"]),
  });
  // ObservationDataSource__audio_transcript__to__text
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/ObservationDataSource",
    toSchemaName: "foxglove_msgs/msg/Log",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertTextLog(message, event, ["audio_transcript"], "audio_transcript"),
  });
  // ObservationDataSource__image__to__image
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/ObservationDataSource",
    toSchemaName: "sensor_msgs/msg/CompressedImage",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["image"], "image"),
  });
  // ObservationDataSource__transcript__to__text
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/ObservationDataSource",
    toSchemaName: "foxglove_msgs/msg/Log",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertTextLog(message, event, ["transcript"], "transcript"),
  });
  // Submission__report_status__to__text
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/Submission",
    toSchemaName: "foxglove_msgs/msg/Log",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertTextLog(message, event, ["report_status"], "report_status"),
  });
  // SupervisorInterfaceSettings__known_casualties_velocity__to__vector_array
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/SupervisorInterfaceSettings",
    toSchemaName: "geometry_msgs/msg/Vector3",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["known_casualties", "velocity"], "vector_array"),
  });
  // TargetBoxArray__source_img__to__image
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/TargetBoxArray",
    toSchemaName: "sensor_msgs/msg/CompressedImage",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertRootStampedImage(message, event, ["source_img"]),
  });
  // TargetHistoryArray__source_img__to__image
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/TargetHistoryArray",
    toSchemaName: "sensor_msgs/msg/CompressedImage",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["source_img"], "image"),
  });
  // Waypoint__orientation__to__orientation
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/Waypoint",
    toSchemaName: "geometry_msgs/msg/Quaternion",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertPassThrough(message, event, ["orientation"], "orientation"),
  });
  // TargetBoxArray__uav_target_boxes__to__image_annotations
  extensionContext.registerMessageConverter({
    type: "schema",
    fromSchemaName: "cdcl_umd_msgs/msg/TargetBoxArray",
    toSchemaName: "foxglove_msgs/msg/ImageAnnotations",
    converter: (message: Immutable<unknown>, event: Immutable<MessageEvent<unknown>>) =>
      convertBoundingBoxAnnotations(message, event, ["uav_target_boxes"]),
  });
}
