// This file is generated by scripts/generate_tba_topic_converters.py.
// Do not edit by hand.

import { ExtensionContext, Immutable, MessageEvent } from "@foxglove/extension";

type AnyMessage = Record<string, unknown>;
type FoxgloveTime = { sec: number; nsec: number };

type TargetBoxArrayConverterConfig = {
  inputTopic: string;
  outputTopic: string;
  uas: number;
  locationField: string;
  locationKey: string;
  locationLabel: string;
};

type RootPassThroughConverterConfig = {
  inputTopic: string;
  outputTopic: string;
  field: string;
  schema: string;
};

type BoundingBoxesConverterConfig = {
  inputTopic: string;
  outputTopic: string;
  uas: number;
  label: string;
};

type Point2D = {
  x: number;
  y: number;
};

const LINE_LOOP = 2;
const FONT_SIZE = 50.0;

function asObject(value: unknown): AnyMessage | undefined {
  if (typeof value !== "object" || value == undefined || Array.isArray(value)) {
    return undefined;
  }

  return value as AnyMessage;
}

function eventTime(event: Immutable<MessageEvent<unknown>>): FoxgloveTime {
  const stamp = event.publishTime ?? event.receiveTime;

  return {
    sec: Number(stamp?.sec ?? 0),
    nsec: Number(stamp?.nsec ?? 0),
  };
}

function eventRosTime(event: Immutable<MessageEvent<unknown>>): { sec: number; nanosec: number } {
  const stamp = eventTime(event);
  return {
    sec: stamp.sec,
    nanosec: stamp.nsec,
  };
}

function normalizeBytes(value: unknown): Uint8Array {
  if (value instanceof Uint8Array) {
    return value;
  }

  if (Array.isArray(value)) {
    return new Uint8Array(value as readonly number[]);
  }

  return new Uint8Array();
}

function normalizeCompressedImageFormat(value: unknown): string {
  const format = String(value ?? "").toLowerCase();

  if (format.includes("jpg") || format.includes("jpeg")) {
    return "jpeg";
  }

  if (format.includes("png")) {
    return "png";
  }

  if (format.includes("tif") || format.includes("tiff")) {
    return "tiff";
  }

  // Most CDCL compressed images are JPEG if not otherwise specified.
  return "jpeg";
}

function isFiniteNumber(value: unknown): value is number {
  return typeof value === "number" && Number.isFinite(value);
}

function isValidNavSatFix(value: unknown): value is AnyMessage {
  const fix = asObject(value);

  if (fix == undefined) {
    return false;
  }

  if (
    !isFiniteNumber(fix.latitude) ||
    !isFiniteNumber(fix.longitude) ||
    Math.abs(fix.latitude) > 90 ||
    Math.abs(fix.longitude) > 180
  ) {
    return false;
  }

  // Treat 0,0 as an unset/invalid localization.
  return !(fix.latitude === 0 && fix.longitude === 0);
}

function navSatFixToCoordinates(fix: AnyMessage): number[] {
  const coordinates = [fix.longitude as number, fix.latitude as number];

  if (isFiniteNumber(fix.altitude)) {
    coordinates.push(fix.altitude);
  }

  return coordinates;
}

function emptyGeoJson(event: Immutable<MessageEvent<unknown>>): Record<string, unknown> {
  return {
    timestamp: eventTime(event),
    frame_id: "",
    geojson: JSON.stringify({
      type: "FeatureCollection",
      features: [],
    }),
  };
}

function rootNavSatFixGeoJson(
  message: unknown,
  event: Immutable<MessageEvent<unknown>>,
  config: TargetBoxArrayConverterConfig,
): Record<string, unknown> {
  const root = asObject(message);
  const fix = root?.[config.locationField];

  if (!isValidNavSatFix(fix)) {
    return emptyGeoJson(event);
  }

  const header = asObject(fix.header);
  const frameId = String(header?.frame_id ?? "");

  return {
    timestamp: eventTime(event),
    frame_id: frameId,
    geojson: JSON.stringify({
      type: "FeatureCollection",
      features: [
        {
          type: "Feature",
          geometry: {
            type: "Point",
            coordinates: navSatFixToCoordinates(fix),
          },
          properties: {
            name: `UAS ${config.uas} ${config.locationLabel}`,
            uas: config.uas,
            location_key: config.locationKey,
            location_field: config.locationField,
            location_label: config.locationLabel,
            source_topic: event.topic,
            latitude: fix.latitude,
            longitude: fix.longitude,
            altitude: fix.altitude,
          },
        },
      ],
    }),
  };
}

function targetBoxesFromMessage(message: unknown): unknown[] {
  const root = asObject(message);
  const boxes = root?.uav_target_boxes;

  if (!Array.isArray(boxes)) {
    return [];
  }

  return boxes;
}

function targetBoxGeoJson(
  message: unknown,
  event: Immutable<MessageEvent<unknown>>,
  config: TargetBoxArrayConverterConfig,
): Record<string, unknown> {
  const features: Record<string, unknown>[] = [];
  let frameId = "";

  const boxes = targetBoxesFromMessage(message);

  boxes.forEach((boxValue, index) => {
    const box = asObject(boxValue);

    if (box == undefined) {
      return;
    }

    const fix = box[config.locationField];

    if (!isValidNavSatFix(fix)) {
      return;
    }

    if (frameId.length === 0) {
      const header = asObject(fix.header);
      frameId = String(header?.frame_id ?? "");
    }

    features.push({
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: navSatFixToCoordinates(fix),
      },
      properties: {
        name: `UAS ${config.uas} ${config.locationLabel} ${index}`,
        uas: config.uas,
        location_key: config.locationKey,
        location_field: config.locationField,
        location_label: config.locationLabel,
        index,
        source_topic: event.topic,
        data_source_id: box.data_source_id,
        detection_class: box.detection_class,
        detection_confidence: box.detection_confidence,
        latitude: fix.latitude,
        longitude: fix.longitude,
        altitude: fix.altitude,
      },
    });
  });

  if (features.length === 0) {
    return emptyGeoJson(event);
  }

  return {
    timestamp: eventTime(event),
    frame_id: frameId,
    geojson: JSON.stringify({
      type: "FeatureCollection",
      features,
    }),
  };
}

function rgba(r: number, g: number, b: number, a: number): Record<string, number> {
  return { r, g, b, a };
}

function rotatePoint(cx: number, cy: number, x: number, y: number, theta: number): Point2D {
  const cosTheta = Math.cos(theta);
  const sinTheta = Math.sin(theta);
  const dx = x - cx;
  const dy = y - cy;

  return {
    x: cx + cosTheta * dx - sinTheta * dy,
    y: cy + sinTheta * dx + cosTheta * dy,
  };
}

function headerStampOrEventTime(
  message: unknown,
  event: Immutable<MessageEvent<unknown>>,
): FoxgloveTime {
  const root = asObject(message);
  const header = asObject(root?.header);
  const stamp = asObject(header?.stamp);

  if (stamp != undefined) {
    return {
      sec: Number(stamp.sec ?? 0),
      nsec: Number(stamp.nsec ?? stamp.nanosec ?? 0),
    };
  }

  return eventTime(event);
}

function boundingBoxesAnnotations(
  message: unknown,
  event: Immutable<MessageEvent<unknown>>,
  config: BoundingBoxesConverterConfig,
): Record<string, unknown> | undefined {
  const boxes = targetBoxesFromMessage(message);

  if (boxes.length === 0) {
    return undefined;
  }

  const timestamp = headerStampOrEventTime(message, event);
  const points: Record<string, unknown>[] = [];
  const texts: Record<string, unknown>[] = [];

  boxes.forEach((boxValue, index) => {
    const targetBox = asObject(boxValue);
    const bbox = asObject(targetBox?.target_bbox);
    const center = asObject(bbox?.center);
    const position = asObject(center?.position);

    if (bbox == undefined || center == undefined || position == undefined) {
      return;
    }

    const cx = Number(position.x);
    const cy = Number(position.y);
    const theta = Number(center.theta ?? 0);
    const sizeX = Number(bbox.size_x);
    const sizeY = Number(bbox.size_y);

    if (
      !Number.isFinite(cx) ||
      !Number.isFinite(cy) ||
      !Number.isFinite(theta) ||
      !Number.isFinite(sizeX) ||
      !Number.isFinite(sizeY) ||
      sizeX <= 0 ||
      sizeY <= 0
    ) {
      return;
    }

    const halfX = sizeX / 2;
    const halfY = sizeY / 2;

    const corners = [
      { x: cx - halfX, y: cy - halfY },
      { x: cx + halfX, y: cy - halfY },
      { x: cx + halfX, y: cy + halfY },
      { x: cx - halfX, y: cy + halfY },
    ].map((point) => rotatePoint(cx, cy, point.x, point.y, theta));

    points.push({
      timestamp,
      type: LINE_LOOP,
      points: corners,
      thickness: 2,
      outline_color: rgba(0, 1, 0, 1),
      outline_colors: [],
      fill_color: rgba(0, 1, 0, 0.12),
    });

    texts.push({
      timestamp,
      position: corners[0],
      text: String(index),
      font_size: FONT_SIZE,
      text_color: rgba(1, 1, 1, 1),
      background_color: rgba(0, 0, 0, 0.6),
    });
  });

  if (points.length === 0 && texts.length === 0) {
    return undefined;
  }

  return {
    circles: [],
    points,
    texts,
  };
}

function rootPassThrough(
  message: unknown,
  event: Immutable<MessageEvent<unknown>>,
  config: RootPassThroughConverterConfig,
): Record<string, unknown> | undefined {
  const root = asObject(message);
  const value = root?.[config.field];

  if (value == undefined) {
    return undefined;
  }

  const objectValue = asObject(value);

  if (objectValue != undefined && config.schema === "sensor_msgs/msg/CompressedImage") {
    return {
      ...objectValue,
      header:
        objectValue.header ??
        {
          stamp: eventRosTime(event),
          frame_id: "",
        },
      format: normalizeCompressedImageFormat(objectValue.format),
      data: normalizeBytes(objectValue.data),
    };
  }

  if (objectValue != undefined && config.schema === "sensor_msgs/msg/Image") {
    return {
      header:
        objectValue.header ??
        {
          stamp: eventRosTime(event),
          frame_id: "",
        },
      height: Number(objectValue.height ?? 0),
      width: Number(objectValue.width ?? 0),
      encoding: String(objectValue.encoding ?? "bgr8"),
      is_bigendian: Number(objectValue.is_bigendian ?? 0),
      step: Number(objectValue.step ?? 0),
      data: normalizeBytes(objectValue.data),
    };
  }

  if (objectValue != undefined) {
    return objectValue;
  }

  return undefined;
}

function registerRootNavSatFixGeoJsonTopicConverter(
  extensionContext: ExtensionContext,
  config: TargetBoxArrayConverterConfig,
): void {
  extensionContext.registerMessageConverter({
    type: "topic",
    inputTopics: [config.inputTopic],
    outputTopic: config.outputTopic,
    outputSchemaName: "foxglove_msgs/msg/GeoJSON",
    create: () => {
      return (messageEvent: Immutable<MessageEvent<unknown>>) =>
        rootNavSatFixGeoJson(messageEvent.message, messageEvent, config);
    },
  });
}

function registerTargetBoxArrayGeoJsonTopicConverter(
  extensionContext: ExtensionContext,
  config: TargetBoxArrayConverterConfig,
): void {
  extensionContext.registerMessageConverter({
    type: "topic",
    inputTopics: [config.inputTopic],
    outputTopic: config.outputTopic,
    outputSchemaName: "foxglove_msgs/msg/GeoJSON",
    create: () => {
      return (messageEvent: Immutable<MessageEvent<unknown>>) =>
        targetBoxGeoJson(messageEvent.message, messageEvent, config);
    },
  });
}

function registerRootPassThroughTopicConverter(
  extensionContext: ExtensionContext,
  config: RootPassThroughConverterConfig,
): void {
  extensionContext.registerMessageConverter({
    type: "topic",
    inputTopics: [config.inputTopic],
    outputTopic: config.outputTopic,
    outputSchemaName: config.schema,
    create: () => {
      return (messageEvent: Immutable<MessageEvent<unknown>>) =>
        rootPassThrough(messageEvent.message, messageEvent, config);
    },
  });
}

function registerBoundingBoxesTopicConverter(
  extensionContext: ExtensionContext,
  config: BoundingBoxesConverterConfig,
): void {
  extensionContext.registerMessageConverter({
    type: "topic",
    inputTopics: [config.inputTopic],
    outputTopic: config.outputTopic,
    outputSchemaName: "foxglove_msgs/msg/ImageAnnotations",
    create: () => {
      return (messageEvent: Immutable<MessageEvent<unknown>>) =>
        boundingBoxesAnnotations(messageEvent.message, messageEvent, config);
    },
  });
}

export function registerGeneratedTbaTopicConverters(extensionContext: ExtensionContext): void {
  registerRootNavSatFixGeoJsonTopicConverter(extensionContext, {
    inputTopic: "/uas1/target_locations",
    outputTopic: "/uas1/target_locations/uav_paused_location",
    uas: 1,
    locationField: "uav_gps_location",
    locationKey: "uav_paused_location",
    locationLabel: "UAV paused location",
  });
  registerRootPassThroughTopicConverter(extensionContext, {
    inputTopic: "/uas1/target_locations",
    outputTopic: "/uas1/target_locations/source_img",
    field: "source_img",
    schema: "sensor_msgs/msg/CompressedImage",
  });
  registerRootPassThroughTopicConverter(extensionContext, {
    inputTopic: "/uas1/target_locations",
    outputTopic: "/uas1/target_locations/uav_local_pose",
    field: "uav_local_pose",
    schema: "nav_msgs/msg/Odometry",
  });
  registerRootPassThroughTopicConverter(extensionContext, {
    inputTopic: "/uas1/target_locations",
    outputTopic: "/uas1/target_locations/gimbal_attitude_quaternion",
    field: "gimbal_attitude_quaternion",
    schema: "geometry_msgs/msg/Quaternion",
  });
  registerBoundingBoxesTopicConverter(extensionContext, {
    inputTopic: "/uas1/target_locations",
    outputTopic: "/uas1/target_locations/bounding_boxes",
    uas: 1,
    label: "Bounding boxes",
  });
  registerTargetBoxArrayGeoJsonTopicConverter(extensionContext, {
    inputTopic: "/uas1/target_locations",
    outputTopic: "/uas1/target_locations/altimeter",
    uas: 1,
    locationField: "target_location_altimeter_plane",
    locationKey: "altimeter",
    locationLabel: "Altimeter plane",
  });
  registerTargetBoxArrayGeoJsonTopicConverter(extensionContext, {
    inputTopic: "/uas1/target_locations",
    outputTopic: "/uas1/target_locations/gimbal",
    uas: 1,
    locationField: "target_location_gimbal_plane",
    locationKey: "gimbal",
    locationLabel: "Gimbal plane",
  });
  registerTargetBoxArrayGeoJsonTopicConverter(extensionContext, {
    inputTopic: "/uas1/target_locations",
    outputTopic: "/uas1/target_locations/rangefinder",
    uas: 1,
    locationField: "target_location_rangefinder",
    locationKey: "rangefinder",
    locationLabel: "Rangefinder",
  });
  registerRootNavSatFixGeoJsonTopicConverter(extensionContext, {
    inputTopic: "/uas1/target_detections",
    outputTopic: "/uas1/target_detections/uav_paused_location",
    uas: 1,
    locationField: "uav_gps_location",
    locationKey: "uav_paused_location",
    locationLabel: "UAV paused location",
  });
  registerRootPassThroughTopicConverter(extensionContext, {
    inputTopic: "/uas1/target_detections",
    outputTopic: "/uas1/target_detections/source_img",
    field: "source_img",
    schema: "sensor_msgs/msg/CompressedImage",
  });
  registerRootPassThroughTopicConverter(extensionContext, {
    inputTopic: "/uas1/target_detections",
    outputTopic: "/uas1/target_detections/uav_local_pose",
    field: "uav_local_pose",
    schema: "nav_msgs/msg/Odometry",
  });
  registerRootPassThroughTopicConverter(extensionContext, {
    inputTopic: "/uas1/target_detections",
    outputTopic: "/uas1/target_detections/gimbal_attitude_quaternion",
    field: "gimbal_attitude_quaternion",
    schema: "geometry_msgs/msg/Quaternion",
  });
  registerBoundingBoxesTopicConverter(extensionContext, {
    inputTopic: "/uas1/target_detections",
    outputTopic: "/uas1/target_detections/bounding_boxes",
    uas: 1,
    label: "Bounding boxes",
  });
  registerRootNavSatFixGeoJsonTopicConverter(extensionContext, {
    inputTopic: "/uas2/target_locations",
    outputTopic: "/uas2/target_locations/uav_paused_location",
    uas: 2,
    locationField: "uav_gps_location",
    locationKey: "uav_paused_location",
    locationLabel: "UAV paused location",
  });
  registerRootPassThroughTopicConverter(extensionContext, {
    inputTopic: "/uas2/target_locations",
    outputTopic: "/uas2/target_locations/source_img",
    field: "source_img",
    schema: "sensor_msgs/msg/CompressedImage",
  });
  registerRootPassThroughTopicConverter(extensionContext, {
    inputTopic: "/uas2/target_locations",
    outputTopic: "/uas2/target_locations/uav_local_pose",
    field: "uav_local_pose",
    schema: "nav_msgs/msg/Odometry",
  });
  registerRootPassThroughTopicConverter(extensionContext, {
    inputTopic: "/uas2/target_locations",
    outputTopic: "/uas2/target_locations/gimbal_attitude_quaternion",
    field: "gimbal_attitude_quaternion",
    schema: "geometry_msgs/msg/Quaternion",
  });
  registerBoundingBoxesTopicConverter(extensionContext, {
    inputTopic: "/uas2/target_locations",
    outputTopic: "/uas2/target_locations/bounding_boxes",
    uas: 2,
    label: "Bounding boxes",
  });
  registerTargetBoxArrayGeoJsonTopicConverter(extensionContext, {
    inputTopic: "/uas2/target_locations",
    outputTopic: "/uas2/target_locations/altimeter",
    uas: 2,
    locationField: "target_location_altimeter_plane",
    locationKey: "altimeter",
    locationLabel: "Altimeter plane",
  });
  registerTargetBoxArrayGeoJsonTopicConverter(extensionContext, {
    inputTopic: "/uas2/target_locations",
    outputTopic: "/uas2/target_locations/gimbal",
    uas: 2,
    locationField: "target_location_gimbal_plane",
    locationKey: "gimbal",
    locationLabel: "Gimbal plane",
  });
  registerTargetBoxArrayGeoJsonTopicConverter(extensionContext, {
    inputTopic: "/uas2/target_locations",
    outputTopic: "/uas2/target_locations/rangefinder",
    uas: 2,
    locationField: "target_location_rangefinder",
    locationKey: "rangefinder",
    locationLabel: "Rangefinder",
  });
  registerRootNavSatFixGeoJsonTopicConverter(extensionContext, {
    inputTopic: "/uas2/target_detections",
    outputTopic: "/uas2/target_detections/uav_paused_location",
    uas: 2,
    locationField: "uav_gps_location",
    locationKey: "uav_paused_location",
    locationLabel: "UAV paused location",
  });
  registerRootPassThroughTopicConverter(extensionContext, {
    inputTopic: "/uas2/target_detections",
    outputTopic: "/uas2/target_detections/source_img",
    field: "source_img",
    schema: "sensor_msgs/msg/CompressedImage",
  });
  registerRootPassThroughTopicConverter(extensionContext, {
    inputTopic: "/uas2/target_detections",
    outputTopic: "/uas2/target_detections/uav_local_pose",
    field: "uav_local_pose",
    schema: "nav_msgs/msg/Odometry",
  });
  registerRootPassThroughTopicConverter(extensionContext, {
    inputTopic: "/uas2/target_detections",
    outputTopic: "/uas2/target_detections/gimbal_attitude_quaternion",
    field: "gimbal_attitude_quaternion",
    schema: "geometry_msgs/msg/Quaternion",
  });
  registerBoundingBoxesTopicConverter(extensionContext, {
    inputTopic: "/uas2/target_detections",
    outputTopic: "/uas2/target_detections/bounding_boxes",
    uas: 2,
    label: "Bounding boxes",
  });
  registerRootNavSatFixGeoJsonTopicConverter(extensionContext, {
    inputTopic: "/uas3/target_locations",
    outputTopic: "/uas3/target_locations/uav_paused_location",
    uas: 3,
    locationField: "uav_gps_location",
    locationKey: "uav_paused_location",
    locationLabel: "UAV paused location",
  });
  registerRootPassThroughTopicConverter(extensionContext, {
    inputTopic: "/uas3/target_locations",
    outputTopic: "/uas3/target_locations/source_img",
    field: "source_img",
    schema: "sensor_msgs/msg/CompressedImage",
  });
  registerRootPassThroughTopicConverter(extensionContext, {
    inputTopic: "/uas3/target_locations",
    outputTopic: "/uas3/target_locations/uav_local_pose",
    field: "uav_local_pose",
    schema: "nav_msgs/msg/Odometry",
  });
  registerRootPassThroughTopicConverter(extensionContext, {
    inputTopic: "/uas3/target_locations",
    outputTopic: "/uas3/target_locations/gimbal_attitude_quaternion",
    field: "gimbal_attitude_quaternion",
    schema: "geometry_msgs/msg/Quaternion",
  });
  registerBoundingBoxesTopicConverter(extensionContext, {
    inputTopic: "/uas3/target_locations",
    outputTopic: "/uas3/target_locations/bounding_boxes",
    uas: 3,
    label: "Bounding boxes",
  });
  registerTargetBoxArrayGeoJsonTopicConverter(extensionContext, {
    inputTopic: "/uas3/target_locations",
    outputTopic: "/uas3/target_locations/altimeter",
    uas: 3,
    locationField: "target_location_altimeter_plane",
    locationKey: "altimeter",
    locationLabel: "Altimeter plane",
  });
  registerTargetBoxArrayGeoJsonTopicConverter(extensionContext, {
    inputTopic: "/uas3/target_locations",
    outputTopic: "/uas3/target_locations/gimbal",
    uas: 3,
    locationField: "target_location_gimbal_plane",
    locationKey: "gimbal",
    locationLabel: "Gimbal plane",
  });
  registerTargetBoxArrayGeoJsonTopicConverter(extensionContext, {
    inputTopic: "/uas3/target_locations",
    outputTopic: "/uas3/target_locations/rangefinder",
    uas: 3,
    locationField: "target_location_rangefinder",
    locationKey: "rangefinder",
    locationLabel: "Rangefinder",
  });
  registerRootNavSatFixGeoJsonTopicConverter(extensionContext, {
    inputTopic: "/uas3/target_detections",
    outputTopic: "/uas3/target_detections/uav_paused_location",
    uas: 3,
    locationField: "uav_gps_location",
    locationKey: "uav_paused_location",
    locationLabel: "UAV paused location",
  });
  registerRootPassThroughTopicConverter(extensionContext, {
    inputTopic: "/uas3/target_detections",
    outputTopic: "/uas3/target_detections/source_img",
    field: "source_img",
    schema: "sensor_msgs/msg/CompressedImage",
  });
  registerRootPassThroughTopicConverter(extensionContext, {
    inputTopic: "/uas3/target_detections",
    outputTopic: "/uas3/target_detections/uav_local_pose",
    field: "uav_local_pose",
    schema: "nav_msgs/msg/Odometry",
  });
  registerRootPassThroughTopicConverter(extensionContext, {
    inputTopic: "/uas3/target_detections",
    outputTopic: "/uas3/target_detections/gimbal_attitude_quaternion",
    field: "gimbal_attitude_quaternion",
    schema: "geometry_msgs/msg/Quaternion",
  });
  registerBoundingBoxesTopicConverter(extensionContext, {
    inputTopic: "/uas3/target_detections",
    outputTopic: "/uas3/target_detections/bounding_boxes",
    uas: 3,
    label: "Bounding boxes",
  });
  registerRootNavSatFixGeoJsonTopicConverter(extensionContext, {
    inputTopic: "/uas4/target_locations",
    outputTopic: "/uas4/target_locations/uav_paused_location",
    uas: 4,
    locationField: "uav_gps_location",
    locationKey: "uav_paused_location",
    locationLabel: "UAV paused location",
  });
  registerRootPassThroughTopicConverter(extensionContext, {
    inputTopic: "/uas4/target_locations",
    outputTopic: "/uas4/target_locations/source_img",
    field: "source_img",
    schema: "sensor_msgs/msg/CompressedImage",
  });
  registerRootPassThroughTopicConverter(extensionContext, {
    inputTopic: "/uas4/target_locations",
    outputTopic: "/uas4/target_locations/uav_local_pose",
    field: "uav_local_pose",
    schema: "nav_msgs/msg/Odometry",
  });
  registerRootPassThroughTopicConverter(extensionContext, {
    inputTopic: "/uas4/target_locations",
    outputTopic: "/uas4/target_locations/gimbal_attitude_quaternion",
    field: "gimbal_attitude_quaternion",
    schema: "geometry_msgs/msg/Quaternion",
  });
  registerBoundingBoxesTopicConverter(extensionContext, {
    inputTopic: "/uas4/target_locations",
    outputTopic: "/uas4/target_locations/bounding_boxes",
    uas: 4,
    label: "Bounding boxes",
  });
  registerTargetBoxArrayGeoJsonTopicConverter(extensionContext, {
    inputTopic: "/uas4/target_locations",
    outputTopic: "/uas4/target_locations/altimeter",
    uas: 4,
    locationField: "target_location_altimeter_plane",
    locationKey: "altimeter",
    locationLabel: "Altimeter plane",
  });
  registerTargetBoxArrayGeoJsonTopicConverter(extensionContext, {
    inputTopic: "/uas4/target_locations",
    outputTopic: "/uas4/target_locations/gimbal",
    uas: 4,
    locationField: "target_location_gimbal_plane",
    locationKey: "gimbal",
    locationLabel: "Gimbal plane",
  });
  registerTargetBoxArrayGeoJsonTopicConverter(extensionContext, {
    inputTopic: "/uas4/target_locations",
    outputTopic: "/uas4/target_locations/rangefinder",
    uas: 4,
    locationField: "target_location_rangefinder",
    locationKey: "rangefinder",
    locationLabel: "Rangefinder",
  });
  registerRootNavSatFixGeoJsonTopicConverter(extensionContext, {
    inputTopic: "/uas4/target_detections",
    outputTopic: "/uas4/target_detections/uav_paused_location",
    uas: 4,
    locationField: "uav_gps_location",
    locationKey: "uav_paused_location",
    locationLabel: "UAV paused location",
  });
  registerRootPassThroughTopicConverter(extensionContext, {
    inputTopic: "/uas4/target_detections",
    outputTopic: "/uas4/target_detections/source_img",
    field: "source_img",
    schema: "sensor_msgs/msg/CompressedImage",
  });
  registerRootPassThroughTopicConverter(extensionContext, {
    inputTopic: "/uas4/target_detections",
    outputTopic: "/uas4/target_detections/uav_local_pose",
    field: "uav_local_pose",
    schema: "nav_msgs/msg/Odometry",
  });
  registerRootPassThroughTopicConverter(extensionContext, {
    inputTopic: "/uas4/target_detections",
    outputTopic: "/uas4/target_detections/gimbal_attitude_quaternion",
    field: "gimbal_attitude_quaternion",
    schema: "geometry_msgs/msg/Quaternion",
  });
  registerBoundingBoxesTopicConverter(extensionContext, {
    inputTopic: "/uas4/target_detections",
    outputTopic: "/uas4/target_detections/bounding_boxes",
    uas: 4,
    label: "Bounding boxes",
  });
}
