// This file is generated by scripts/generate_tba_topic_converters.py.
// Do not edit by hand.

import { ExtensionContext, Immutable, MessageEvent } from "@foxglove/extension";

type AnyMessage = Record<string, unknown>;
type FoxgloveTime = { sec: number; nsec: number };

type TargetBoxArrayConverterConfig = {
  inputTopic: string;
  outputTopic: string;
  uas: number;
  locationField: string;
  locationKey: string;
  locationLabel: string;
};

type RootPassThroughConverterConfig = {
  inputTopic: string;
  outputTopic: string;
  field: string;
  schema: string;
};

function asObject(value: unknown): AnyMessage | undefined {
  if (typeof value !== "object" || value == undefined || Array.isArray(value)) {
    return undefined;
  }

  return value as AnyMessage;
}

function eventTime(event: Immutable<MessageEvent<unknown>>): FoxgloveTime {
  const stamp = event.publishTime ?? event.receiveTime;

  return {
    sec: Number(stamp?.sec ?? 0),
    nsec: Number(stamp?.nsec ?? 0),
  };
}

function isFiniteNumber(value: unknown): value is number {
  return typeof value === "number" && Number.isFinite(value);
}

function isValidNavSatFix(value: unknown): value is AnyMessage {
  const fix = asObject(value);

  if (fix == undefined) {
    return false;
  }

  if (
    !isFiniteNumber(fix.latitude) ||
    !isFiniteNumber(fix.longitude) ||
    Math.abs(fix.latitude) > 90 ||
    Math.abs(fix.longitude) > 180
  ) {
    return false;
  }

  // Treat 0,0 as an unset/invalid localization.
  return !(fix.latitude === 0 && fix.longitude === 0);
}

function navSatFixToCoordinates(fix: AnyMessage): number[] {
  const coordinates = [fix.longitude as number, fix.latitude as number];

  if (isFiniteNumber(fix.altitude)) {
    coordinates.push(fix.altitude);
  }

  return coordinates;
}

function emptyGeoJson(event: Immutable<MessageEvent<unknown>>): Record<string, unknown> {
  return {
    timestamp: eventTime(event),
    frame_id: "",
    geojson: JSON.stringify({
      type: "FeatureCollection",
      features: [],
    }),
  };
}

function rootNavSatFixGeoJson(
  message: unknown,
  event: Immutable<MessageEvent<unknown>>,
  config: TargetBoxArrayConverterConfig,
): Record<string, unknown> {
  const root = asObject(message);
  const fix = root?.[config.locationField];

  if (!isValidNavSatFix(fix)) {
    return emptyGeoJson(event);
  }

  const header = asObject(fix.header);
  const frameId = String(header?.frame_id ?? "");

  return {
    timestamp: eventTime(event),
    frame_id: frameId,
    geojson: JSON.stringify({
      type: "FeatureCollection",
      features: [
        {
          type: "Feature",
          geometry: {
            type: "Point",
            coordinates: navSatFixToCoordinates(fix),
          },
          properties: {
            name: `UAS ${config.uas} ${config.locationLabel}`,
            uas: config.uas,
            location_key: config.locationKey,
            location_field: config.locationField,
            location_label: config.locationLabel,
            source_topic: event.topic,
            latitude: fix.latitude,
            longitude: fix.longitude,
            altitude: fix.altitude,
          },
        },
      ],
    }),
  };
}

function targetBoxesFromMessage(message: unknown): unknown[] {
  const root = asObject(message);
  const boxes = root?.uav_target_boxes;

  if (!Array.isArray(boxes)) {
    return [];
  }

  return boxes;
}

function targetBoxGeoJson(
  message: unknown,
  event: Immutable<MessageEvent<unknown>>,
  config: TargetBoxArrayConverterConfig,
): Record<string, unknown> {
  const features: Record<string, unknown>[] = [];
  let frameId = "";

  const boxes = targetBoxesFromMessage(message);

  boxes.forEach((boxValue, index) => {
    const box = asObject(boxValue);

    if (box == undefined) {
      return;
    }

    const fix = box[config.locationField];

    if (!isValidNavSatFix(fix)) {
      return;
    }

    if (frameId.length === 0) {
      const header = asObject(fix.header);
      frameId = String(header?.frame_id ?? "");
    }

    features.push({
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: navSatFixToCoordinates(fix),
      },
      properties: {
        name: `UAS ${config.uas} ${config.locationLabel} ${index}`,
        uas: config.uas,
        location_key: config.locationKey,
        location_field: config.locationField,
        location_label: config.locationLabel,
        index,
        source_topic: event.topic,
        data_source_id: box.data_source_id,
        detection_class: box.detection_class,
        detection_confidence: box.detection_confidence,
        latitude: fix.latitude,
        longitude: fix.longitude,
        altitude: fix.altitude,
      },
    });
  });

  if (features.length === 0) {
    return emptyGeoJson(event);
  }

  return {
    timestamp: eventTime(event),
    frame_id: frameId,
    geojson: JSON.stringify({
      type: "FeatureCollection",
      features,
    }),
  };
}

function rootPassThrough(
  message: unknown,
  config: RootPassThroughConverterConfig,
): Record<string, unknown> | undefined {
  const root = asObject(message);
  const value = root?.[config.field];

  if (value == undefined) {
    return undefined;
  }

  const objectValue = asObject(value);

  if (objectValue != undefined) {
    return objectValue;
  }

  return undefined;
}

function registerRootNavSatFixGeoJsonTopicConverter(
  extensionContext: ExtensionContext,
  config: TargetBoxArrayConverterConfig,
): void {
  extensionContext.registerMessageConverter({
    type: "topic",
    inputTopics: [config.inputTopic],
    outputTopic: config.outputTopic,
    outputSchemaName: "foxglove_msgs/msg/GeoJSON",
    create: () => {
      return (messageEvent: Immutable<MessageEvent<unknown>>) =>
        rootNavSatFixGeoJson(messageEvent.message, messageEvent, config);
    },
  });
}

function registerTargetBoxArrayGeoJsonTopicConverter(
  extensionContext: ExtensionContext,
  config: TargetBoxArrayConverterConfig,
): void {
  extensionContext.registerMessageConverter({
    type: "topic",
    inputTopics: [config.inputTopic],
    outputTopic: config.outputTopic,
    outputSchemaName: "foxglove_msgs/msg/GeoJSON",
    create: () => {
      return (messageEvent: Immutable<MessageEvent<unknown>>) =>
        targetBoxGeoJson(messageEvent.message, messageEvent, config);
    },
  });
}

function registerRootPassThroughTopicConverter(
  extensionContext: ExtensionContext,
  config: RootPassThroughConverterConfig,
): void {
  extensionContext.registerMessageConverter({
    type: "topic",
    inputTopics: [config.inputTopic],
    outputTopic: config.outputTopic,
    outputSchemaName: config.schema,
    create: () => {
      return (messageEvent: Immutable<MessageEvent<unknown>>) =>
        rootPassThrough(messageEvent.message, config);
    },
  });
}

export function registerGeneratedTbaTopicConverters(extensionContext: ExtensionContext): void {
  registerRootNavSatFixGeoJsonTopicConverter(extensionContext, {
    inputTopic: "/uas1/target_locations",
    outputTopic: "/uas1/target_locations/uav_paused_location",
    uas: 1,
    locationField: "uav_gps_location",
    locationKey: "uav_paused_location",
    locationLabel: "UAV paused location",
  });
  registerRootPassThroughTopicConverter(extensionContext, {
    inputTopic: "/uas1/target_locations",
    outputTopic: "/uas1/target_locations/uav_local_pose",
    field: "uav_local_pose",
    schema: "nav_msgs/msg/Odometry",
  });
  registerRootPassThroughTopicConverter(extensionContext, {
    inputTopic: "/uas1/target_locations",
    outputTopic: "/uas1/target_locations/gimbal_attitude_quaternion",
    field: "gimbal_attitude_quaternion",
    schema: "geometry_msgs/msg/Quaternion",
  });
  registerTargetBoxArrayGeoJsonTopicConverter(extensionContext, {
    inputTopic: "/uas1/target_locations",
    outputTopic: "/uas1/target_locations/altimeter",
    uas: 1,
    locationField: "target_location_altimeter_plane",
    locationKey: "altimeter",
    locationLabel: "Altimeter plane",
  });
  registerTargetBoxArrayGeoJsonTopicConverter(extensionContext, {
    inputTopic: "/uas1/target_locations",
    outputTopic: "/uas1/target_locations/gimbal",
    uas: 1,
    locationField: "target_location_gimbal_plane",
    locationKey: "gimbal",
    locationLabel: "Gimbal plane",
  });
  registerTargetBoxArrayGeoJsonTopicConverter(extensionContext, {
    inputTopic: "/uas1/target_locations",
    outputTopic: "/uas1/target_locations/rangefinder",
    uas: 1,
    locationField: "target_location_rangefinder",
    locationKey: "rangefinder",
    locationLabel: "Rangefinder",
  });
  registerRootNavSatFixGeoJsonTopicConverter(extensionContext, {
    inputTopic: "/uas1/target_detections",
    outputTopic: "/uas1/target_detections/uav_paused_location",
    uas: 1,
    locationField: "uav_gps_location",
    locationKey: "uav_paused_location",
    locationLabel: "UAV paused location",
  });
  registerRootPassThroughTopicConverter(extensionContext, {
    inputTopic: "/uas1/target_detections",
    outputTopic: "/uas1/target_detections/uav_local_pose",
    field: "uav_local_pose",
    schema: "nav_msgs/msg/Odometry",
  });
  registerRootPassThroughTopicConverter(extensionContext, {
    inputTopic: "/uas1/target_detections",
    outputTopic: "/uas1/target_detections/gimbal_attitude_quaternion",
    field: "gimbal_attitude_quaternion",
    schema: "geometry_msgs/msg/Quaternion",
  });
  registerRootNavSatFixGeoJsonTopicConverter(extensionContext, {
    inputTopic: "/uas2/target_locations",
    outputTopic: "/uas2/target_locations/uav_paused_location",
    uas: 2,
    locationField: "uav_gps_location",
    locationKey: "uav_paused_location",
    locationLabel: "UAV paused location",
  });
  registerRootPassThroughTopicConverter(extensionContext, {
    inputTopic: "/uas2/target_locations",
    outputTopic: "/uas2/target_locations/uav_local_pose",
    field: "uav_local_pose",
    schema: "nav_msgs/msg/Odometry",
  });
  registerRootPassThroughTopicConverter(extensionContext, {
    inputTopic: "/uas2/target_locations",
    outputTopic: "/uas2/target_locations/gimbal_attitude_quaternion",
    field: "gimbal_attitude_quaternion",
    schema: "geometry_msgs/msg/Quaternion",
  });
  registerTargetBoxArrayGeoJsonTopicConverter(extensionContext, {
    inputTopic: "/uas2/target_locations",
    outputTopic: "/uas2/target_locations/altimeter",
    uas: 2,
    locationField: "target_location_altimeter_plane",
    locationKey: "altimeter",
    locationLabel: "Altimeter plane",
  });
  registerTargetBoxArrayGeoJsonTopicConverter(extensionContext, {
    inputTopic: "/uas2/target_locations",
    outputTopic: "/uas2/target_locations/gimbal",
    uas: 2,
    locationField: "target_location_gimbal_plane",
    locationKey: "gimbal",
    locationLabel: "Gimbal plane",
  });
  registerTargetBoxArrayGeoJsonTopicConverter(extensionContext, {
    inputTopic: "/uas2/target_locations",
    outputTopic: "/uas2/target_locations/rangefinder",
    uas: 2,
    locationField: "target_location_rangefinder",
    locationKey: "rangefinder",
    locationLabel: "Rangefinder",
  });
  registerRootNavSatFixGeoJsonTopicConverter(extensionContext, {
    inputTopic: "/uas2/target_detections",
    outputTopic: "/uas2/target_detections/uav_paused_location",
    uas: 2,
    locationField: "uav_gps_location",
    locationKey: "uav_paused_location",
    locationLabel: "UAV paused location",
  });
  registerRootPassThroughTopicConverter(extensionContext, {
    inputTopic: "/uas2/target_detections",
    outputTopic: "/uas2/target_detections/uav_local_pose",
    field: "uav_local_pose",
    schema: "nav_msgs/msg/Odometry",
  });
  registerRootPassThroughTopicConverter(extensionContext, {
    inputTopic: "/uas2/target_detections",
    outputTopic: "/uas2/target_detections/gimbal_attitude_quaternion",
    field: "gimbal_attitude_quaternion",
    schema: "geometry_msgs/msg/Quaternion",
  });
  registerRootNavSatFixGeoJsonTopicConverter(extensionContext, {
    inputTopic: "/uas3/target_locations",
    outputTopic: "/uas3/target_locations/uav_paused_location",
    uas: 3,
    locationField: "uav_gps_location",
    locationKey: "uav_paused_location",
    locationLabel: "UAV paused location",
  });
  registerRootPassThroughTopicConverter(extensionContext, {
    inputTopic: "/uas3/target_locations",
    outputTopic: "/uas3/target_locations/uav_local_pose",
    field: "uav_local_pose",
    schema: "nav_msgs/msg/Odometry",
  });
  registerRootPassThroughTopicConverter(extensionContext, {
    inputTopic: "/uas3/target_locations",
    outputTopic: "/uas3/target_locations/gimbal_attitude_quaternion",
    field: "gimbal_attitude_quaternion",
    schema: "geometry_msgs/msg/Quaternion",
  });
  registerTargetBoxArrayGeoJsonTopicConverter(extensionContext, {
    inputTopic: "/uas3/target_locations",
    outputTopic: "/uas3/target_locations/altimeter",
    uas: 3,
    locationField: "target_location_altimeter_plane",
    locationKey: "altimeter",
    locationLabel: "Altimeter plane",
  });
  registerTargetBoxArrayGeoJsonTopicConverter(extensionContext, {
    inputTopic: "/uas3/target_locations",
    outputTopic: "/uas3/target_locations/gimbal",
    uas: 3,
    locationField: "target_location_gimbal_plane",
    locationKey: "gimbal",
    locationLabel: "Gimbal plane",
  });
  registerTargetBoxArrayGeoJsonTopicConverter(extensionContext, {
    inputTopic: "/uas3/target_locations",
    outputTopic: "/uas3/target_locations/rangefinder",
    uas: 3,
    locationField: "target_location_rangefinder",
    locationKey: "rangefinder",
    locationLabel: "Rangefinder",
  });
  registerRootNavSatFixGeoJsonTopicConverter(extensionContext, {
    inputTopic: "/uas3/target_detections",
    outputTopic: "/uas3/target_detections/uav_paused_location",
    uas: 3,
    locationField: "uav_gps_location",
    locationKey: "uav_paused_location",
    locationLabel: "UAV paused location",
  });
  registerRootPassThroughTopicConverter(extensionContext, {
    inputTopic: "/uas3/target_detections",
    outputTopic: "/uas3/target_detections/uav_local_pose",
    field: "uav_local_pose",
    schema: "nav_msgs/msg/Odometry",
  });
  registerRootPassThroughTopicConverter(extensionContext, {
    inputTopic: "/uas3/target_detections",
    outputTopic: "/uas3/target_detections/gimbal_attitude_quaternion",
    field: "gimbal_attitude_quaternion",
    schema: "geometry_msgs/msg/Quaternion",
  });
  registerRootNavSatFixGeoJsonTopicConverter(extensionContext, {
    inputTopic: "/uas4/target_locations",
    outputTopic: "/uas4/target_locations/uav_paused_location",
    uas: 4,
    locationField: "uav_gps_location",
    locationKey: "uav_paused_location",
    locationLabel: "UAV paused location",
  });
  registerRootPassThroughTopicConverter(extensionContext, {
    inputTopic: "/uas4/target_locations",
    outputTopic: "/uas4/target_locations/uav_local_pose",
    field: "uav_local_pose",
    schema: "nav_msgs/msg/Odometry",
  });
  registerRootPassThroughTopicConverter(extensionContext, {
    inputTopic: "/uas4/target_locations",
    outputTopic: "/uas4/target_locations/gimbal_attitude_quaternion",
    field: "gimbal_attitude_quaternion",
    schema: "geometry_msgs/msg/Quaternion",
  });
  registerTargetBoxArrayGeoJsonTopicConverter(extensionContext, {
    inputTopic: "/uas4/target_locations",
    outputTopic: "/uas4/target_locations/altimeter",
    uas: 4,
    locationField: "target_location_altimeter_plane",
    locationKey: "altimeter",
    locationLabel: "Altimeter plane",
  });
  registerTargetBoxArrayGeoJsonTopicConverter(extensionContext, {
    inputTopic: "/uas4/target_locations",
    outputTopic: "/uas4/target_locations/gimbal",
    uas: 4,
    locationField: "target_location_gimbal_plane",
    locationKey: "gimbal",
    locationLabel: "Gimbal plane",
  });
  registerTargetBoxArrayGeoJsonTopicConverter(extensionContext, {
    inputTopic: "/uas4/target_locations",
    outputTopic: "/uas4/target_locations/rangefinder",
    uas: 4,
    locationField: "target_location_rangefinder",
    locationKey: "rangefinder",
    locationLabel: "Rangefinder",
  });
  registerRootNavSatFixGeoJsonTopicConverter(extensionContext, {
    inputTopic: "/uas4/target_detections",
    outputTopic: "/uas4/target_detections/uav_paused_location",
    uas: 4,
    locationField: "uav_gps_location",
    locationKey: "uav_paused_location",
    locationLabel: "UAV paused location",
  });
  registerRootPassThroughTopicConverter(extensionContext, {
    inputTopic: "/uas4/target_detections",
    outputTopic: "/uas4/target_detections/uav_local_pose",
    field: "uav_local_pose",
    schema: "nav_msgs/msg/Odometry",
  });
  registerRootPassThroughTopicConverter(extensionContext, {
    inputTopic: "/uas4/target_detections",
    outputTopic: "/uas4/target_detections/gimbal_attitude_quaternion",
    field: "gimbal_attitude_quaternion",
    schema: "geometry_msgs/msg/Quaternion",
  });
}
