// Generated by scripts/generate_converters.py. Do not edit by hand.
//
// Data only: every conversion behaviour lives in ./converterRuntime.ts.

import { SchemaConverterSpec, TopicConverterSpec } from "./converterRuntime";

export const SCHEMA_CONVERTER_SPECS: readonly SchemaConverterSpec[] =
  [
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/Assessment",
    "toSchemaName": "sensor_msgs/msg/NavSatFix",
    "op": {
      "kind": "navsatfix",
      "path": [
        "location"
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/CameraFOV",
    "toSchemaName": "foxglove_msgs/msg/GeoJSON",
    "op": {
      "kind": "geojson",
      "entries": [
        {
          "path": [
            "fov_polygon"
          ],
          "label": "Fov polygon",
          "geometry": "polygon",
          "color": "#46f0f0",
          "propertyFields": [
            "coverage_area"
          ]
        }
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/CameraPose",
    "toSchemaName": "geometry_msgs/msg/Pose",
    "op": {
      "kind": "passthrough",
      "path": [
        "pose"
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/CasualtyImage",
    "toSchemaName": "geometry_msgs/msg/Point",
    "op": {
      "kind": "passthrough",
      "path": [
        "position_in_sensor_frame"
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/CasualtyImage",
    "toSchemaName": "sensor_msgs/msg/Image",
    "op": {
      "kind": "image",
      "path": [
        "image"
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/CasualtyImage",
    "toSchemaName": "sensor_msgs/msg/NavSatFix",
    "op": {
      "kind": "navsatfix",
      "path": [
        "position"
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/CasualtyImageCompressed",
    "toSchemaName": "geometry_msgs/msg/Point",
    "op": {
      "kind": "passthrough",
      "path": [
        "position_in_sensor_frame"
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/CasualtyImageCompressed",
    "toSchemaName": "sensor_msgs/msg/CompressedImage",
    "op": {
      "kind": "image",
      "path": [
        "image"
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/CasualtyImageCompressed",
    "toSchemaName": "sensor_msgs/msg/NavSatFix",
    "op": {
      "kind": "navsatfix",
      "path": [
        "position"
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/CasualtyImageWithLevel",
    "toSchemaName": "geometry_msgs/msg/Point",
    "op": {
      "kind": "passthrough",
      "path": [
        "position_in_sensor_frame"
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/CasualtyImageWithLevel",
    "toSchemaName": "sensor_msgs/msg/Image",
    "op": {
      "kind": "image",
      "path": [
        "image"
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/CasualtyImageWithLevel",
    "toSchemaName": "sensor_msgs/msg/NavSatFix",
    "op": {
      "kind": "navsatfix",
      "path": [
        "position"
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/CasualtyLocation",
    "toSchemaName": "sensor_msgs/msg/NavSatFix",
    "op": {
      "kind": "navsatfix",
      "path": [
        "position"
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/CasualtyReport",
    "toSchemaName": "foxglove_msgs/msg/GeoJSON",
    "op": {
      "kind": "geojson",
      "entries": [
        {
          "path": [
            "position_submitted"
          ],
          "label": "Position submitted",
          "geometry": "point",
          "color": "#000075",
          "propertyFields": [
            "casualty_id",
            "level",
            "track_status",
            "track_hits",
            "total_measurements",
            "image_submitted"
          ]
        }
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/CasualtyReport",
    "toSchemaName": "geometry_msgs/msg/Vector3",
    "op": {
      "kind": "passthrough",
      "path": [
        "velocity"
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/CasualtyReport",
    "toSchemaName": "sensor_msgs/msg/NavSatFix",
    "op": {
      "kind": "navsatfix",
      "path": [
        "position"
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/CenterROI",
    "toSchemaName": "geometry_msgs/msg/Quaternion",
    "op": {
      "kind": "passthrough",
      "path": [
        "gimbal_attitude_quaternion"
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/CenterROI",
    "toSchemaName": "nav_msgs/msg/Odometry",
    "op": {
      "kind": "passthrough",
      "path": [
        "uav_local_pose"
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/Geofence",
    "toSchemaName": "foxglove_msgs/msg/GeoJSON",
    "op": {
      "kind": "geojson",
      "entries": [
        {
          "path": [
            "coordinates"
          ],
          "label": "Coordinates",
          "geometry": "polygon",
          "color": "#4363d8"
        }
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/KnownCasualtyLocations",
    "toSchemaName": "foxglove_msgs/msg/GeoJSON",
    "op": {
      "kind": "geojson",
      "entries": [
        {
          "path": [
            "casualty_locations",
            "position"
          ],
          "label": "Position",
          "geometry": "point",
          "color": "#008080",
          "propertyFields": [
            "casualty_id"
          ]
        }
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/MedicUpdate",
    "toSchemaName": "sensor_msgs/msg/NavSatFix",
    "op": {
      "kind": "navsatfix",
      "path": [
        "position"
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/MosaicOverlay",
    "toSchemaName": "sensor_msgs/msg/CompressedImage",
    "op": {
      "kind": "image",
      "path": [
        "overlay_png"
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/Observation",
    "toSchemaName": "sensor_msgs/msg/NavSatFix",
    "op": {
      "kind": "navsatfix",
      "path": [
        "position"
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/ObservationDataSource",
    "toSchemaName": "foxglove_msgs/msg/Log",
    "op": {
      "kind": "log",
      "entries": [
        {
          "path": [
            "audio_transcript"
          ],
          "label": "Audio transcript"
        },
        {
          "path": [
            "transcript"
          ],
          "label": "Transcript"
        }
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/ObservationDataSource",
    "toSchemaName": "foxglove_msgs/msg/RawAudio",
    "op": {
      "kind": "audio",
      "path": [
        "raw_audio"
      ],
      "stampPath": [
        "audio_start"
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/ObservationDataSource",
    "toSchemaName": "sensor_msgs/msg/CompressedImage",
    "op": {
      "kind": "image",
      "path": [
        "image"
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/ObservationWithLevel",
    "toSchemaName": "sensor_msgs/msg/NavSatFix",
    "op": {
      "kind": "navsatfix",
      "path": [
        "position"
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/RadarTarget",
    "toSchemaName": "geometry_msgs/msg/Vector3",
    "op": {
      "kind": "passthrough",
      "path": [
        "position"
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/Submission",
    "toSchemaName": "sensor_msgs/msg/NavSatFix",
    "op": {
      "kind": "navsatfix",
      "path": [
        "assessment",
        "location"
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/SupervisorInterfaceSettings",
    "toSchemaName": "foxglove_msgs/msg/GeoJSON",
    "op": {
      "kind": "geojson",
      "entries": [
        {
          "path": [
            "geo_fence"
          ],
          "label": "Geo fence",
          "geometry": "polygon",
          "color": "#3cb44b",
          "propertyFields": [
            "gate",
            "time_of_day",
            "run_duration_min",
            "darpa_server_ip",
            "active_mobile_assets",
            "ground_truth_csv_path",
            "inference_engine_path"
          ]
        },
        {
          "path": [
            "search_domain"
          ],
          "label": "Search domain",
          "geometry": "polygon",
          "color": "#f58231",
          "propertyFields": [
            "gate",
            "time_of_day",
            "run_duration_min",
            "darpa_server_ip",
            "active_mobile_assets",
            "ground_truth_csv_path",
            "inference_engine_path"
          ]
        },
        {
          "path": [
            "launch_zone"
          ],
          "label": "Launch zone",
          "geometry": "polygon",
          "color": "#9a6324",
          "propertyFields": [
            "gate",
            "time_of_day",
            "run_duration_min",
            "darpa_server_ip",
            "active_mobile_assets",
            "ground_truth_csv_path",
            "inference_engine_path"
          ]
        },
        {
          "path": [
            "known_casualties",
            "position"
          ],
          "label": "Position",
          "geometry": "point",
          "color": "#f032e6",
          "propertyFields": [
            "casualty_id",
            "level",
            "track_status",
            "track_hits",
            "total_measurements",
            "image_submitted"
          ]
        },
        {
          "path": [
            "known_casualties",
            "position_submitted"
          ],
          "label": "Position submitted",
          "geometry": "point",
          "color": "#e6194b",
          "propertyFields": [
            "casualty_id",
            "level",
            "track_status",
            "track_hits",
            "total_measurements",
            "image_submitted"
          ]
        },
        {
          "path": [
            "exclusion_zones",
            "coordinates"
          ],
          "label": "Coordinates",
          "geometry": "polygon",
          "color": "#008080"
        }
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/TargetBox",
    "toSchemaName": "foxglove_msgs/msg/GeoJSON",
    "op": {
      "kind": "geojson",
      "entries": [
        {
          "path": [
            "target_location_gimbal_plane"
          ],
          "label": "Target location gimbal plane",
          "geometry": "point",
          "color": "#46f0f0",
          "propertyFields": [
            "data_source_id",
            "use_for_assessment",
            "detection_class",
            "detection_confidence"
          ]
        },
        {
          "path": [
            "target_location_rangefinder"
          ],
          "label": "Target location rangefinder",
          "geometry": "point",
          "color": "#000075",
          "propertyFields": [
            "data_source_id",
            "use_for_assessment",
            "detection_class",
            "detection_confidence"
          ]
        }
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/TargetBox",
    "toSchemaName": "foxglove_msgs/msg/ImageAnnotations",
    "op": {
      "kind": "image_annotations",
      "entries": [
        {
          "containerPath": [],
          "bboxField": "target_bbox",
          "labelFields": [
            "detection_class",
            "detection_confidence"
          ],
          "color": "#e6194b"
        }
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/TargetBox",
    "toSchemaName": "sensor_msgs/msg/NavSatFix",
    "op": {
      "kind": "navsatfix",
      "path": [
        "target_location_altimeter_plane"
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/TargetBoxArray",
    "toSchemaName": "foxglove_msgs/msg/ImageAnnotations",
    "op": {
      "kind": "image_annotations",
      "entries": [
        {
          "containerPath": [
            "uav_target_boxes"
          ],
          "bboxField": "target_bbox",
          "labelFields": [
            "detection_class",
            "detection_confidence"
          ],
          "color": "#008080"
        }
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/TargetBoxArray",
    "toSchemaName": "geometry_msgs/msg/Quaternion",
    "op": {
      "kind": "passthrough",
      "path": [
        "gimbal_attitude_quaternion"
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/TargetBoxArray",
    "toSchemaName": "nav_msgs/msg/Odometry",
    "op": {
      "kind": "passthrough",
      "path": [
        "uav_local_pose"
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/TargetBoxArray",
    "toSchemaName": "sensor_msgs/msg/CompressedImage",
    "op": {
      "kind": "image",
      "path": [
        "source_img"
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/TargetBoxArray",
    "toSchemaName": "sensor_msgs/msg/NavSatFix",
    "op": {
      "kind": "navsatfix",
      "path": [
        "uav_gps_location"
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/TargetHistoryArray",
    "toSchemaName": "foxglove_msgs/msg/GeoJSON",
    "op": {
      "kind": "geojson",
      "entries": [
        {
          "path": [
            "target_locations",
            "target_location_intrinsics"
          ],
          "label": "Target location intrinsics",
          "geometry": "point",
          "color": "#a9a9a9",
          "propertyFields": [
            "target_id",
            "detection_class",
            "detection_confidence",
            "use_for_assessment"
          ]
        },
        {
          "path": [
            "target_locations",
            "target_location_topo"
          ],
          "label": "Target location topo",
          "geometry": "point",
          "color": "#008080",
          "propertyFields": [
            "target_id",
            "detection_class",
            "detection_confidence",
            "use_for_assessment"
          ]
        },
        {
          "path": [
            "target_locations",
            "target_location_gimbal_plane"
          ],
          "label": "Target location gimbal plane",
          "geometry": "point",
          "color": "#bcf60c",
          "propertyFields": [
            "target_id",
            "detection_class",
            "detection_confidence",
            "use_for_assessment"
          ]
        },
        {
          "path": [
            "target_locations",
            "target_location_rangefinder"
          ],
          "label": "Target location rangefinder",
          "geometry": "point",
          "color": "#e6194b",
          "propertyFields": [
            "target_id",
            "detection_class",
            "detection_confidence",
            "use_for_assessment"
          ]
        }
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/TargetHistoryArray",
    "toSchemaName": "foxglove_msgs/msg/ImageAnnotations",
    "op": {
      "kind": "image_annotations",
      "entries": [
        {
          "containerPath": [
            "target_locations"
          ],
          "bboxField": "target_bbox",
          "labelFields": [
            "detection_class",
            "detection_confidence"
          ],
          "color": "#fabebe"
        }
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/TargetHistoryArray",
    "toSchemaName": "sensor_msgs/msg/CompressedImage",
    "op": {
      "kind": "image",
      "path": [
        "source_img"
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/TargetLocation",
    "toSchemaName": "foxglove_msgs/msg/GeoJSON",
    "op": {
      "kind": "geojson",
      "entries": [
        {
          "path": [
            "target_location_topo"
          ],
          "label": "Target location topo",
          "geometry": "point",
          "color": "#808000",
          "propertyFields": [
            "target_id",
            "detection_class",
            "detection_confidence",
            "use_for_assessment"
          ]
        },
        {
          "path": [
            "target_location_gimbal_plane"
          ],
          "label": "Target location gimbal plane",
          "geometry": "point",
          "color": "#f58231",
          "propertyFields": [
            "target_id",
            "detection_class",
            "detection_confidence",
            "use_for_assessment"
          ]
        },
        {
          "path": [
            "target_location_rangefinder"
          ],
          "label": "Target location rangefinder",
          "geometry": "point",
          "color": "#a9a9a9",
          "propertyFields": [
            "target_id",
            "detection_class",
            "detection_confidence",
            "use_for_assessment"
          ]
        }
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/TargetLocation",
    "toSchemaName": "foxglove_msgs/msg/ImageAnnotations",
    "op": {
      "kind": "image_annotations",
      "entries": [
        {
          "containerPath": [],
          "bboxField": "target_bbox",
          "labelFields": [
            "detection_class",
            "detection_confidence"
          ],
          "color": "#46f0f0"
        }
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/TargetLocation",
    "toSchemaName": "sensor_msgs/msg/NavSatFix",
    "op": {
      "kind": "navsatfix",
      "path": [
        "target_location_intrinsics"
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/TopicNetworkStatus",
    "toSchemaName": "foxglove_msgs/msg/Log",
    "op": {
      "kind": "log",
      "entries": [
        {
          "path": [
            "message_type"
          ],
          "label": "Message type"
        }
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/Waypoint",
    "toSchemaName": "geometry_msgs/msg/Quaternion",
    "op": {
      "kind": "passthrough",
      "path": [
        "orientation"
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/Waypoint",
    "toSchemaName": "sensor_msgs/msg/NavSatFix",
    "op": {
      "kind": "navsatfix",
      "path": [
        "position"
      ]
    }
  },
  {
    "fromSchemaName": "cdcl_umd_msgs/msg/WaypointArray",
    "toSchemaName": "foxglove_msgs/msg/GeoJSON",
    "op": {
      "kind": "geojson",
      "entries": [
        {
          "path": [
            "waypoints",
            "position"
          ],
          "label": "Position",
          "geometry": "point",
          "color": "#3cb44b",
          "propertyFields": [
            "id",
            "seq",
            "casualty_visit",
            "casualty_id",
            "arrival_time",
            "departure_time",
            "visit_status",
            "score"
          ]
        }
      ]
    }
  }
];

export const TOPIC_CONVERTER_SPECS: readonly TopicConverterSpec[] =
  [
  {
    "inputTopic": "/uas1/target_locations",
    "outputTopic": "/uas1/target_locations/altimeter",
    "outputSchemaName": "foxglove_msgs/msg/GeoJSON",
    "op": {
      "kind": "geojson",
      "entries": [
        {
          "path": [
            "uav_target_boxes",
            "target_location_altimeter_plane"
          ],
          "label": "Altimeter",
          "geometry": "point",
          "color": "#fabebe",
          "propertyFields": [
            "data_source_id",
            "use_for_assessment",
            "detection_class",
            "detection_confidence"
          ]
        }
      ]
    }
  },
  {
    "inputTopic": "/uas1/target_locations",
    "outputTopic": "/uas1/target_locations/gimbal",
    "outputSchemaName": "foxglove_msgs/msg/GeoJSON",
    "op": {
      "kind": "geojson",
      "entries": [
        {
          "path": [
            "uav_target_boxes",
            "target_location_gimbal_plane"
          ],
          "label": "Gimbal",
          "geometry": "point",
          "color": "#9a6324",
          "propertyFields": [
            "data_source_id",
            "use_for_assessment",
            "detection_class",
            "detection_confidence"
          ]
        }
      ]
    }
  },
  {
    "inputTopic": "/uas1/target_locations",
    "outputTopic": "/uas1/target_locations/rangefinder",
    "outputSchemaName": "foxglove_msgs/msg/GeoJSON",
    "op": {
      "kind": "geojson",
      "entries": [
        {
          "path": [
            "uav_target_boxes",
            "target_location_rangefinder"
          ],
          "label": "Rangefinder",
          "geometry": "point",
          "color": "#46f0f0",
          "propertyFields": [
            "data_source_id",
            "use_for_assessment",
            "detection_class",
            "detection_confidence"
          ]
        }
      ]
    }
  },
  {
    "inputTopic": "/uas1/tf_localization/localized",
    "outputTopic": "/uas1/tf_localization/localized/altimeter",
    "outputSchemaName": "foxglove_msgs/msg/GeoJSON",
    "op": {
      "kind": "geojson",
      "entries": [
        {
          "path": [
            "uav_target_boxes",
            "target_location_altimeter_plane"
          ],
          "label": "Altimeter",
          "geometry": "point",
          "color": "#fabebe",
          "propertyFields": [
            "data_source_id",
            "use_for_assessment",
            "detection_class",
            "detection_confidence"
          ]
        }
      ]
    }
  },
  {
    "inputTopic": "/uas1/tf_localization/localized",
    "outputTopic": "/uas1/tf_localization/localized/gimbal",
    "outputSchemaName": "foxglove_msgs/msg/GeoJSON",
    "op": {
      "kind": "geojson",
      "entries": [
        {
          "path": [
            "uav_target_boxes",
            "target_location_gimbal_plane"
          ],
          "label": "Gimbal",
          "geometry": "point",
          "color": "#9a6324",
          "propertyFields": [
            "data_source_id",
            "use_for_assessment",
            "detection_class",
            "detection_confidence"
          ]
        }
      ]
    }
  },
  {
    "inputTopic": "/uas1/tf_localization/localized",
    "outputTopic": "/uas1/tf_localization/localized/rangefinder",
    "outputSchemaName": "foxglove_msgs/msg/GeoJSON",
    "op": {
      "kind": "geojson",
      "entries": [
        {
          "path": [
            "uav_target_boxes",
            "target_location_rangefinder"
          ],
          "label": "Rangefinder",
          "geometry": "point",
          "color": "#46f0f0",
          "propertyFields": [
            "data_source_id",
            "use_for_assessment",
            "detection_class",
            "detection_confidence"
          ]
        }
      ]
    }
  },
  {
    "inputTopic": "/uas2/target_locations",
    "outputTopic": "/uas2/target_locations/altimeter",
    "outputSchemaName": "foxglove_msgs/msg/GeoJSON",
    "op": {
      "kind": "geojson",
      "entries": [
        {
          "path": [
            "uav_target_boxes",
            "target_location_altimeter_plane"
          ],
          "label": "Altimeter",
          "geometry": "point",
          "color": "#fabebe",
          "propertyFields": [
            "data_source_id",
            "use_for_assessment",
            "detection_class",
            "detection_confidence"
          ]
        }
      ]
    }
  },
  {
    "inputTopic": "/uas2/target_locations",
    "outputTopic": "/uas2/target_locations/gimbal",
    "outputSchemaName": "foxglove_msgs/msg/GeoJSON",
    "op": {
      "kind": "geojson",
      "entries": [
        {
          "path": [
            "uav_target_boxes",
            "target_location_gimbal_plane"
          ],
          "label": "Gimbal",
          "geometry": "point",
          "color": "#9a6324",
          "propertyFields": [
            "data_source_id",
            "use_for_assessment",
            "detection_class",
            "detection_confidence"
          ]
        }
      ]
    }
  },
  {
    "inputTopic": "/uas2/target_locations",
    "outputTopic": "/uas2/target_locations/rangefinder",
    "outputSchemaName": "foxglove_msgs/msg/GeoJSON",
    "op": {
      "kind": "geojson",
      "entries": [
        {
          "path": [
            "uav_target_boxes",
            "target_location_rangefinder"
          ],
          "label": "Rangefinder",
          "geometry": "point",
          "color": "#46f0f0",
          "propertyFields": [
            "data_source_id",
            "use_for_assessment",
            "detection_class",
            "detection_confidence"
          ]
        }
      ]
    }
  },
  {
    "inputTopic": "/uas2/tf_localization/localized",
    "outputTopic": "/uas2/tf_localization/localized/altimeter",
    "outputSchemaName": "foxglove_msgs/msg/GeoJSON",
    "op": {
      "kind": "geojson",
      "entries": [
        {
          "path": [
            "uav_target_boxes",
            "target_location_altimeter_plane"
          ],
          "label": "Altimeter",
          "geometry": "point",
          "color": "#fabebe",
          "propertyFields": [
            "data_source_id",
            "use_for_assessment",
            "detection_class",
            "detection_confidence"
          ]
        }
      ]
    }
  },
  {
    "inputTopic": "/uas2/tf_localization/localized",
    "outputTopic": "/uas2/tf_localization/localized/gimbal",
    "outputSchemaName": "foxglove_msgs/msg/GeoJSON",
    "op": {
      "kind": "geojson",
      "entries": [
        {
          "path": [
            "uav_target_boxes",
            "target_location_gimbal_plane"
          ],
          "label": "Gimbal",
          "geometry": "point",
          "color": "#9a6324",
          "propertyFields": [
            "data_source_id",
            "use_for_assessment",
            "detection_class",
            "detection_confidence"
          ]
        }
      ]
    }
  },
  {
    "inputTopic": "/uas2/tf_localization/localized",
    "outputTopic": "/uas2/tf_localization/localized/rangefinder",
    "outputSchemaName": "foxglove_msgs/msg/GeoJSON",
    "op": {
      "kind": "geojson",
      "entries": [
        {
          "path": [
            "uav_target_boxes",
            "target_location_rangefinder"
          ],
          "label": "Rangefinder",
          "geometry": "point",
          "color": "#46f0f0",
          "propertyFields": [
            "data_source_id",
            "use_for_assessment",
            "detection_class",
            "detection_confidence"
          ]
        }
      ]
    }
  },
  {
    "inputTopic": "/uas3/target_locations",
    "outputTopic": "/uas3/target_locations/altimeter",
    "outputSchemaName": "foxglove_msgs/msg/GeoJSON",
    "op": {
      "kind": "geojson",
      "entries": [
        {
          "path": [
            "uav_target_boxes",
            "target_location_altimeter_plane"
          ],
          "label": "Altimeter",
          "geometry": "point",
          "color": "#fabebe",
          "propertyFields": [
            "data_source_id",
            "use_for_assessment",
            "detection_class",
            "detection_confidence"
          ]
        }
      ]
    }
  },
  {
    "inputTopic": "/uas3/target_locations",
    "outputTopic": "/uas3/target_locations/gimbal",
    "outputSchemaName": "foxglove_msgs/msg/GeoJSON",
    "op": {
      "kind": "geojson",
      "entries": [
        {
          "path": [
            "uav_target_boxes",
            "target_location_gimbal_plane"
          ],
          "label": "Gimbal",
          "geometry": "point",
          "color": "#9a6324",
          "propertyFields": [
            "data_source_id",
            "use_for_assessment",
            "detection_class",
            "detection_confidence"
          ]
        }
      ]
    }
  },
  {
    "inputTopic": "/uas3/target_locations",
    "outputTopic": "/uas3/target_locations/rangefinder",
    "outputSchemaName": "foxglove_msgs/msg/GeoJSON",
    "op": {
      "kind": "geojson",
      "entries": [
        {
          "path": [
            "uav_target_boxes",
            "target_location_rangefinder"
          ],
          "label": "Rangefinder",
          "geometry": "point",
          "color": "#46f0f0",
          "propertyFields": [
            "data_source_id",
            "use_for_assessment",
            "detection_class",
            "detection_confidence"
          ]
        }
      ]
    }
  },
  {
    "inputTopic": "/uas3/tf_localization/localized",
    "outputTopic": "/uas3/tf_localization/localized/altimeter",
    "outputSchemaName": "foxglove_msgs/msg/GeoJSON",
    "op": {
      "kind": "geojson",
      "entries": [
        {
          "path": [
            "uav_target_boxes",
            "target_location_altimeter_plane"
          ],
          "label": "Altimeter",
          "geometry": "point",
          "color": "#fabebe",
          "propertyFields": [
            "data_source_id",
            "use_for_assessment",
            "detection_class",
            "detection_confidence"
          ]
        }
      ]
    }
  },
  {
    "inputTopic": "/uas3/tf_localization/localized",
    "outputTopic": "/uas3/tf_localization/localized/gimbal",
    "outputSchemaName": "foxglove_msgs/msg/GeoJSON",
    "op": {
      "kind": "geojson",
      "entries": [
        {
          "path": [
            "uav_target_boxes",
            "target_location_gimbal_plane"
          ],
          "label": "Gimbal",
          "geometry": "point",
          "color": "#9a6324",
          "propertyFields": [
            "data_source_id",
            "use_for_assessment",
            "detection_class",
            "detection_confidence"
          ]
        }
      ]
    }
  },
  {
    "inputTopic": "/uas3/tf_localization/localized",
    "outputTopic": "/uas3/tf_localization/localized/rangefinder",
    "outputSchemaName": "foxglove_msgs/msg/GeoJSON",
    "op": {
      "kind": "geojson",
      "entries": [
        {
          "path": [
            "uav_target_boxes",
            "target_location_rangefinder"
          ],
          "label": "Rangefinder",
          "geometry": "point",
          "color": "#46f0f0",
          "propertyFields": [
            "data_source_id",
            "use_for_assessment",
            "detection_class",
            "detection_confidence"
          ]
        }
      ]
    }
  },
  {
    "inputTopic": "/uas4/target_locations",
    "outputTopic": "/uas4/target_locations/altimeter",
    "outputSchemaName": "foxglove_msgs/msg/GeoJSON",
    "op": {
      "kind": "geojson",
      "entries": [
        {
          "path": [
            "uav_target_boxes",
            "target_location_altimeter_plane"
          ],
          "label": "Altimeter",
          "geometry": "point",
          "color": "#fabebe",
          "propertyFields": [
            "data_source_id",
            "use_for_assessment",
            "detection_class",
            "detection_confidence"
          ]
        }
      ]
    }
  },
  {
    "inputTopic": "/uas4/target_locations",
    "outputTopic": "/uas4/target_locations/gimbal",
    "outputSchemaName": "foxglove_msgs/msg/GeoJSON",
    "op": {
      "kind": "geojson",
      "entries": [
        {
          "path": [
            "uav_target_boxes",
            "target_location_gimbal_plane"
          ],
          "label": "Gimbal",
          "geometry": "point",
          "color": "#9a6324",
          "propertyFields": [
            "data_source_id",
            "use_for_assessment",
            "detection_class",
            "detection_confidence"
          ]
        }
      ]
    }
  },
  {
    "inputTopic": "/uas4/target_locations",
    "outputTopic": "/uas4/target_locations/rangefinder",
    "outputSchemaName": "foxglove_msgs/msg/GeoJSON",
    "op": {
      "kind": "geojson",
      "entries": [
        {
          "path": [
            "uav_target_boxes",
            "target_location_rangefinder"
          ],
          "label": "Rangefinder",
          "geometry": "point",
          "color": "#46f0f0",
          "propertyFields": [
            "data_source_id",
            "use_for_assessment",
            "detection_class",
            "detection_confidence"
          ]
        }
      ]
    }
  },
  {
    "inputTopic": "/uas4/tf_localization/localized",
    "outputTopic": "/uas4/tf_localization/localized/altimeter",
    "outputSchemaName": "foxglove_msgs/msg/GeoJSON",
    "op": {
      "kind": "geojson",
      "entries": [
        {
          "path": [
            "uav_target_boxes",
            "target_location_altimeter_plane"
          ],
          "label": "Altimeter",
          "geometry": "point",
          "color": "#fabebe",
          "propertyFields": [
            "data_source_id",
            "use_for_assessment",
            "detection_class",
            "detection_confidence"
          ]
        }
      ]
    }
  },
  {
    "inputTopic": "/uas4/tf_localization/localized",
    "outputTopic": "/uas4/tf_localization/localized/gimbal",
    "outputSchemaName": "foxglove_msgs/msg/GeoJSON",
    "op": {
      "kind": "geojson",
      "entries": [
        {
          "path": [
            "uav_target_boxes",
            "target_location_gimbal_plane"
          ],
          "label": "Gimbal",
          "geometry": "point",
          "color": "#9a6324",
          "propertyFields": [
            "data_source_id",
            "use_for_assessment",
            "detection_class",
            "detection_confidence"
          ]
        }
      ]
    }
  },
  {
    "inputTopic": "/uas4/tf_localization/localized",
    "outputTopic": "/uas4/tf_localization/localized/rangefinder",
    "outputSchemaName": "foxglove_msgs/msg/GeoJSON",
    "op": {
      "kind": "geojson",
      "entries": [
        {
          "path": [
            "uav_target_boxes",
            "target_location_rangefinder"
          ],
          "label": "Rangefinder",
          "geometry": "point",
          "color": "#46f0f0",
          "propertyFields": [
            "data_source_id",
            "use_for_assessment",
            "detection_class",
            "detection_confidence"
          ]
        }
      ]
    }
  }
];
