#!/usr/bin/env python3
"""Helpers for writing generated TypeScript into the extension packages."""
from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
RUNTIME_SOURCE = REPO_ROOT / "shared" / "converterRuntime.ts"
RUNTIME_BASENAME = "converterRuntime.ts"

GENERATED_BANNER = "// Generated by {script}. Do not edit by hand."


def ts_literal(value: object, indent: int = 2) -> str:
    """Serializes plain data as a TypeScript literal (JSON is valid TS)."""
    return json.dumps(value, indent=indent, ensure_ascii=False)


def write_if_changed(path: Path, content: str) -> bool:
    """Writes `content` to `path`, returning True when the file actually changed."""
    path.parent.mkdir(parents=True, exist_ok=True)

    if path.exists() and path.read_text() == content:
        return False

    path.write_text(content)
    return True


def sync_runtime(dest_dir: Path) -> Path:
    """Copies the shared converter runtime into a generated directory."""
    if not RUNTIME_SOURCE.exists():
        raise SystemExit(f"Shared converter runtime not found: {RUNTIME_SOURCE}")

    dest = dest_dir / RUNTIME_BASENAME
    header = (
        f"// Copied from shared/{RUNTIME_BASENAME} by the converter generators.\n"
        f"// Do not edit this copy; edit shared/{RUNTIME_BASENAME} and re-run "
        f"`npm run generate`.\n\n"
    )

    write_if_changed(dest, header + RUNTIME_SOURCE.read_text())
    return dest


def remove_stale(paths: list[Path]) -> list[Path]:
    """Deletes superseded generated files, returning the ones that existed."""
    removed = []

    for path in paths:
        if path.exists():
            path.unlink()
            removed.append(path)

    return removed
